<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ApprenantsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('apprenants')->delete();
        
        \DB::table('apprenants')->insert(array (
            0 => 
            array (
                'id' => 1,
                'matricule' => 'US-B-01',
                'nom' => 'Malik',
                'prenom' => 'Moctar',
                'adresse' => NULL,
                'sexe' => 'Masculin',
                'date_naissance' => '2018-04-25',
                'lieu_naissance' => 'Niamey',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-26 14:00:39',
                'updated_at' => '2023-10-26 14:00:39',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'matricule' => 'US-B-02',
                'nom' => 'Sharafardine',
                'prenom' => 'Mahamane Ibrah',
                'adresse' => NULL,
                'sexe' => 'Masculin',
                'date_naissance' => '2017-12-12',
                'lieu_naissance' => 'Zinder',
                'telephone' => '96633002',
                'etablissement_id' => 1,
                'created_at' => '2023-10-26 14:06:11',
                'updated_at' => '2023-10-26 14:06:11',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'matricule' => 'US-B-03',
                'nom' => 'Sani',
                'prenom' => 'Saboulou',
                'adresse' => NULL,
                'sexe' => 'Masculin',
                'date_naissance' => '2017-12-25',
                'lieu_naissance' => 'Zinder',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-27 05:12:57',
                'updated_at' => '2023-10-27 05:12:57',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'matricule' => 'US-B-04',
                'nom' => 'Rakia',
                'prenom' => 'Moussa Dan Dare',
                'adresse' => NULL,
                'sexe' => 'Féminin',
                'date_naissance' => '2018-05-12',
                'lieu_naissance' => 'Dosso',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-27 05:14:08',
                'updated_at' => '2023-10-27 05:14:08',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'matricule' => 'US-B-05',
                'nom' => 'Rachida',
                'prenom' => 'Masahi Kanfo',
                'adresse' => NULL,
                'sexe' => 'Féminin',
                'date_naissance' => '2018-11-24',
                'lieu_naissance' => 'Maradi',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-27 05:15:31',
                'updated_at' => '2023-10-27 05:15:31',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'matricule' => 'US-B-06',
                'nom' => 'Zaharadine',
                'prenom' => 'Daouda',
                'adresse' => NULL,
                'sexe' => 'Masculin',
                'date_naissance' => '2017-03-24',
                'lieu_naissance' => 'Gazaoua',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-27 05:17:52',
                'updated_at' => '2023-10-27 05:17:52',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'matricule' => 'US-B-07',
                'nom' => 'Saydatou',
                'prenom' => 'Yougbare',
                'adresse' => NULL,
                'sexe' => 'Féminin',
                'date_naissance' => '2018-11-30',
                'lieu_naissance' => 'Ouaga',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-27 05:19:25',
                'updated_at' => '2023-10-27 05:19:25',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'matricule' => 'US-B-08',
                'nom' => 'Ismael',
                'prenom' => 'Sunna',
                'adresse' => NULL,
                'sexe' => 'Masculin',
                'date_naissance' => '2016-02-25',
                'lieu_naissance' => 'Niamey',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-27 05:20:29',
                'updated_at' => '2023-10-27 05:20:29',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'matricule' => 'US-B-09',
                'nom' => 'Hassane',
                'prenom' => 'aissatou',
                'adresse' => NULL,
                'sexe' => 'Féminin',
                'date_naissance' => '2017-03-04',
                'lieu_naissance' => 'Agadez',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-28 07:17:31',
                'updated_at' => '2023-10-28 07:17:31',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'matricule' => 'US-B-010',
                'nom' => 'Ismail',
                'prenom' => 'Moctar',
                'adresse' => NULL,
                'sexe' => 'Masculin',
                'date_naissance' => '2018-01-12',
                'lieu_naissance' => 'Diffa',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-28 07:21:17',
                'updated_at' => '2023-10-28 07:21:17',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'matricule' => 'US-B-011',
                'nom' => 'Rachida',
                'prenom' => 'Cherif',
                'adresse' => NULL,
                'sexe' => 'Féminin',
                'date_naissance' => '2018-03-08',
                'lieu_naissance' => 'Niamey',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-28 07:23:11',
                'updated_at' => '2023-10-28 07:23:11',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'matricule' => 'US-B-012',
                'nom' => 'Asmaou',
                'prenom' => 'Illiassou',
                'adresse' => NULL,
                'sexe' => 'Féminin',
                'date_naissance' => '2017-12-31',
                'lieu_naissance' => 'Maradi',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-28 07:24:47',
                'updated_at' => '2023-10-28 07:24:47',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'matricule' => 'US-B-013',
                'nom' => 'Halima',
                'prenom' => 'Sani',
                'adresse' => NULL,
                'sexe' => 'Féminin',
                'date_naissance' => '2018-12-23',
                'lieu_naissance' => 'Niamey',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-28 07:26:05',
                'updated_at' => '2023-10-28 07:26:05',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'matricule' => 'US-B-014',
                'nom' => 'Boucharatou',
                'prenom' => 'Kabirou',
                'adresse' => NULL,
                'sexe' => 'Féminin',
                'date_naissance' => '2018-12-23',
                'lieu_naissance' => 'Niamey',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-28 07:30:11',
                'updated_at' => '2023-10-28 07:30:11',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'matricule' => 'US-B-015',
                'nom' => 'Bouraima',
                'prenom' => 'Adamou',
                'adresse' => NULL,
                'sexe' => 'Masculin',
                'date_naissance' => '2017-12-05',
                'lieu_naissance' => 'Arlit',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-28 14:14:54',
                'updated_at' => '2023-10-28 14:14:54',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'matricule' => 'US-B-016',
                'nom' => 'Issa',
                'prenom' => 'Abdoul Latif',
                'adresse' => NULL,
                'sexe' => 'Masculin',
                'date_naissance' => '2018-12-20',
                'lieu_naissance' => 'Niamey',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-28 14:18:00',
                'updated_at' => '2023-10-28 14:18:00',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'matricule' => 'US-B-017',
                'nom' => 'Nafissa',
                'prenom' => 'Zakari',
                'adresse' => NULL,
                'sexe' => 'Féminin',
                'date_naissance' => '2017-12-08',
                'lieu_naissance' => 'Niamey',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-28 14:19:43',
                'updated_at' => '2023-10-28 14:19:43',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'matricule' => 'US-B-018',
                'nom' => 'Illias',
                'prenom' => 'Mahamadou',
                'adresse' => NULL,
                'sexe' => 'Masculin',
                'date_naissance' => '2018-12-25',
                'lieu_naissance' => 'Niamey',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-28 14:21:26',
                'updated_at' => '2023-10-28 14:21:26',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'matricule' => 'US-B-019',
                'nom' => 'Mohamed',
                'prenom' => 'Alio',
                'adresse' => NULL,
                'sexe' => 'Masculin',
                'date_naissance' => '2018-02-01',
                'lieu_naissance' => 'Tillabery',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-28 14:23:24',
                'updated_at' => '2023-10-28 14:23:24',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'matricule' => 'US-B-020',
                'nom' => 'Youssouf',
                'prenom' => 'lamine',
                'adresse' => NULL,
                'sexe' => 'Masculin',
                'date_naissance' => '2018-01-17',
                'lieu_naissance' => 'Niamey',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-28 14:26:05',
                'updated_at' => '2023-10-28 14:26:05',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'matricule' => 'US-B-021',
                'nom' => 'Ousmane',
                'prenom' => 'Arzika',
                'adresse' => NULL,
                'sexe' => 'Masculin',
                'date_naissance' => '2017-03-12',
                'lieu_naissance' => 'Niamey',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-28 14:27:37',
                'updated_at' => '2023-10-28 14:27:37',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'matricule' => 'US-B-022',
                'nom' => 'Kamilou',
                'prenom' => 'Aboubacar',
                'adresse' => NULL,
                'sexe' => 'Masculin',
                'date_naissance' => '2011-11-02',
                'lieu_naissance' => 'Niamey',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-28 15:09:28',
                'updated_at' => '2023-10-28 15:09:28',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'matricule' => 'US-B-023',
                'nom' => 'Roukaya',
                'prenom' => 'Nassirou',
                'adresse' => NULL,
                'sexe' => 'Féminin',
                'date_naissance' => '2012-12-12',
                'lieu_naissance' => 'Niamey',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-28 15:12:18',
                'updated_at' => '2023-10-28 15:12:18',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'matricule' => 'US-B-024',
                'nom' => 'Hama',
                'prenom' => 'Rachidou',
                'adresse' => NULL,
                'sexe' => 'Masculin',
                'date_naissance' => '2011-11-23',
                'lieu_naissance' => 'Pais',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-28 15:13:52',
                'updated_at' => '2023-10-28 15:13:52',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'matricule' => 'US-B-025',
                'nom' => 'Ibro',
                'prenom' => 'Chekaraou',
                'adresse' => NULL,
                'sexe' => 'Masculin',
                'date_naissance' => '2012-01-25',
                'lieu_naissance' => 'Arlit',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-28 15:15:19',
                'updated_at' => '2023-10-28 15:15:19',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'matricule' => 'US-B-026',
                'nom' => 'Zabeirou',
                'prenom' => 'Kalla',
                'adresse' => NULL,
                'sexe' => 'Masculin',
                'date_naissance' => '2012-10-11',
                'lieu_naissance' => 'Maradi',
                'telephone' => '90007712',
                'etablissement_id' => 1,
                'created_at' => '2023-10-30 10:51:53',
                'updated_at' => '2023-10-30 10:51:53',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'matricule' => 'US-B-027',
                'nom' => 'Hamissou',
                'prenom' => 'Labaran',
                'adresse' => NULL,
                'sexe' => 'Masculin',
                'date_naissance' => '2011-11-09',
                'lieu_naissance' => 'Tera',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-30 11:01:47',
                'updated_at' => '2023-10-30 11:01:47',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'matricule' => 'US-B-028',
                'nom' => 'Zouhouratou',
                'prenom' => 'Djibo',
                'adresse' => NULL,
                'sexe' => 'Féminin',
                'date_naissance' => '2012-08-10',
                'lieu_naissance' => 'Arlit',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-30 11:04:18',
                'updated_at' => '2023-10-30 11:04:18',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'matricule' => 'US-B-029',
                'nom' => 'Barkatou',
                'prenom' => 'Aminou',
                'adresse' => NULL,
                'sexe' => 'Féminin',
                'date_naissance' => '2011-07-01',
                'lieu_naissance' => 'Tannout',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-30 11:05:47',
                'updated_at' => '2023-10-30 11:05:47',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'matricule' => 'US-B-030',
                'nom' => 'Maidawa',
                'prenom' => 'Boubacar',
                'adresse' => NULL,
                'sexe' => 'Masculin',
                'date_naissance' => '2013-10-04',
                'lieu_naissance' => 'Mai sasape',
                'telephone' => '90898990',
                'etablissement_id' => 1,
                'created_at' => '2023-10-30 11:08:46',
                'updated_at' => '2023-10-30 11:08:46',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'matricule' => 'US-B-031',
                'nom' => 'Faïza',
                'prenom' => 'Bettou',
                'adresse' => NULL,
                'sexe' => 'Féminin',
                'date_naissance' => '2011-04-09',
                'lieu_naissance' => 'Hamdallah',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-30 11:10:32',
                'updated_at' => '2023-10-30 11:10:32',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'matricule' => 'US-B-032',
                'nom' => 'Nafiou',
                'prenom' => 'Bonkaney',
                'adresse' => NULL,
                'sexe' => 'Masculin',
                'date_naissance' => '2013-01-10',
                'lieu_naissance' => 'Barchawal',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-30 11:12:01',
                'updated_at' => '2023-10-30 11:12:01',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'matricule' => 'US-B-033',
                'nom' => 'Sarifatou',
                'prenom' => 'Namata',
                'adresse' => NULL,
                'sexe' => 'Féminin',
                'date_naissance' => '2012-11-15',
                'lieu_naissance' => 'Gidan Rumji',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-30 11:13:41',
                'updated_at' => '2023-10-30 11:13:41',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'matricule' => 'US-B-034',
                'nom' => 'Issaka',
                'prenom' => 'Dan Takoussa',
                'adresse' => NULL,
                'sexe' => 'Masculin',
                'date_naissance' => '2013-07-20',
                'lieu_naissance' => 'Koure',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-30 11:15:21',
                'updated_at' => '2023-10-30 11:15:21',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'matricule' => 'US-B-035',
                'nom' => 'Hari',
                'prenom' => 'Chipkaou',
                'adresse' => NULL,
                'sexe' => 'Féminin',
                'date_naissance' => '2012-11-01',
                'lieu_naissance' => 'Wakasso',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-30 11:17:11',
                'updated_at' => '2023-10-30 11:17:11',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'matricule' => 'US-B-036',
                'nom' => 'Abouba',
                'prenom' => 'Alambouzou',
                'adresse' => NULL,
                'sexe' => 'Masculin',
                'date_naissance' => '2011-11-04',
                'lieu_naissance' => 'Israel',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-30 11:19:07',
                'updated_at' => '2023-10-30 11:19:07',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'matricule' => 'US-B-037',
                'nom' => 'Rouwaida',
                'prenom' => 'Wahab',
                'adresse' => NULL,
                'sexe' => 'Féminin',
                'date_naissance' => '2011-10-13',
                'lieu_naissance' => 'Nassarawa',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-30 11:20:50',
                'updated_at' => '2023-10-30 11:20:50',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'matricule' => 'US-B-038',
                'nom' => 'Saoudatou',
                'prenom' => 'Awal',
                'adresse' => NULL,
                'sexe' => 'Féminin',
                'date_naissance' => '2011-10-16',
                'lieu_naissance' => 'Gaya',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-30 11:22:40',
                'updated_at' => '2023-10-30 11:22:40',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'matricule' => 'US-B-039',
                'nom' => 'Lamine',
                'prenom' => 'Mayaki',
                'adresse' => NULL,
                'sexe' => 'Masculin',
                'date_naissance' => '2011-08-05',
                'lieu_naissance' => 'Nord',
                'telephone' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-30 12:12:37',
                'updated_at' => '2023-10-30 12:12:37',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}