<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class EnseignantsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('enseignants')->delete();
        
        \DB::table('enseignants')->insert(array (
            0 => 
            array (
                'id' => 1,
                'matricule' => 'MAT/11E',
                'nom' => 'Sani',
                'prenom' => 'Sale',
                'sex' => 'Masculin',
                'date_naissance' => '1984-12-02',
                'lieu_naissance' => 'Niamey',
                'telephone' => '9646023',
                'compte' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-26 13:26:06',
                'updated_at' => '2023-10-26 13:26:06',
                'deleted_at' => NULL,
                'NomComplet' => 'Sani Sale',
                'date_lieu_nais' => '1984-12-02 à Niamey',
            ),
            1 => 
            array (
                'id' => 2,
                'matricule' => 'MAT/12E',
                'nom' => 'Hapsou',
                'prenom' => 'Sandi',
                'sex' => 'Féminin',
                'date_naissance' => '2000-02-01',
                'lieu_naissance' => 'Tera',
                'telephone' => '92301220',
                'compte' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-26 13:29:13',
                'updated_at' => '2023-10-26 13:29:13',
                'deleted_at' => NULL,
                'NomComplet' => 'Hapsou Sandi',
                'date_lieu_nais' => '2000-02-01 à Tera',
            ),
            2 => 
            array (
                'id' => 3,
                'matricule' => 'MAT/13E',
                'nom' => 'Fati',
                'prenom' => 'Abdou',
                'sex' => 'Féminin',
                'date_naissance' => '1999-02-01',
                'lieu_naissance' => 'Mayayi',
                'telephone' => '88451220',
                'compte' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-26 13:32:11',
                'updated_at' => '2023-10-26 13:32:11',
                'deleted_at' => NULL,
                'NomComplet' => 'Fati Abdou',
                'date_lieu_nais' => '1999-02-01 à Mayayi',
            ),
            3 => 
            array (
                'id' => 4,
                'matricule' => 'MAT/14E',
                'nom' => 'Jamila',
                'prenom' => 'Hadi',
                'sex' => 'Féminin',
                'date_naissance' => '1986-03-30',
                'lieu_naissance' => 'Maradi',
                'telephone' => '88663321',
                'compte' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-26 13:34:03',
                'updated_at' => '2023-10-26 13:34:03',
                'deleted_at' => NULL,
                'NomComplet' => 'Jamila Hadi',
                'date_lieu_nais' => '1986-03-30 à Maradi',
            ),
            4 => 
            array (
                'id' => 5,
                'matricule' => 'MAT/15E',
                'nom' => 'Hamza',
                'prenom' => 'Hassan',
                'sex' => 'Masculin',
                'date_naissance' => '1996-05-14',
                'lieu_naissance' => 'Tahoua',
                'telephone' => '94563210',
                'compte' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-26 13:37:04',
                'updated_at' => '2023-10-26 13:37:04',
                'deleted_at' => NULL,
                'NomComplet' => 'Hamza Hassan',
                'date_lieu_nais' => '1996-05-14 à Tahoua',
            ),
            5 => 
            array (
                'id' => 6,
                'matricule' => 'MAT/16E',
                'nom' => 'Karim',
                'prenom' => 'Badoo',
                'sex' => 'Masculin',
                'date_naissance' => '1979-03-13',
                'lieu_naissance' => 'Bosso',
                'telephone' => '97895632',
                'compte' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-26 13:40:01',
                'updated_at' => '2023-10-26 13:40:01',
                'deleted_at' => NULL,
                'NomComplet' => 'Karim Badoo',
                'date_lieu_nais' => '1979-03-13 à Bosso',
            ),
            6 => 
            array (
                'id' => 7,
                'matricule' => 'MAT/17E',
                'nom' => 'Lamin',
                'prenom' => 'Arji',
                'sex' => 'Masculin',
                'date_naissance' => '1995-08-11',
                'lieu_naissance' => 'Arlit',
                'telephone' => '89562320',
                'compte' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-26 13:42:43',
                'updated_at' => '2023-10-26 13:42:43',
                'deleted_at' => NULL,
                'NomComplet' => 'Lamin Arji',
                'date_lieu_nais' => '1995-08-11 à Arlit',
            ),
            7 => 
            array (
                'id' => 8,
                'matricule' => 'MAT/18E',
                'nom' => 'Malik',
                'prenom' => 'Maliki',
                'sex' => 'Masculin',
                'date_naissance' => '1974-12-25',
                'lieu_naissance' => 'May Sasap',
                'telephone' => '80301542',
                'compte' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-26 13:45:37',
                'updated_at' => '2023-10-26 13:45:37',
                'deleted_at' => NULL,
                'NomComplet' => 'Malik Maliki',
                'date_lieu_nais' => '1974-12-25 à May Sasap',
            ),
            8 => 
            array (
                'id' => 9,
                'matricule' => 'MAT/19E',
                'nom' => 'Yves',
                'prenom' => 'Bego',
                'sex' => 'Masculin',
                'date_naissance' => '1994-11-26',
                'lieu_naissance' => 'Tessaoua',
                'telephone' => '89656542',
                'compte' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-26 13:54:33',
                'updated_at' => '2023-10-26 13:54:33',
                'deleted_at' => NULL,
                'NomComplet' => 'Yves Bego',
                'date_lieu_nais' => '1994-11-26 à Tessaoua',
            ),
            9 => 
            array (
                'id' => 10,
                'matricule' => 'MAT/110E',
                'nom' => 'Hannatou',
                'prenom' => 'Jaha',
                'sex' => 'Féminin',
                'date_naissance' => '1996-12-02',
                'lieu_naissance' => 'Niamey',
                'telephone' => '93122030',
                'compte' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-26 13:56:03',
                'updated_at' => '2023-10-26 13:56:03',
                'deleted_at' => NULL,
                'NomComplet' => 'Hannatou Jaha',
                'date_lieu_nais' => '1996-12-02 à Niamey',
            ),
            10 => 
            array (
                'id' => 11,
                'matricule' => 'MAT/111E',
                'nom' => 'Adrika',
                'prenom' => 'Koumale',
                'sex' => 'Masculin',
                'date_naissance' => '2000-06-08',
                'lieu_naissance' => 'Cotonou',
                'telephone' => '90112100',
                'compte' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-30 10:06:50',
                'updated_at' => '2023-10-30 10:06:50',
                'deleted_at' => NULL,
                'NomComplet' => 'Adrika Koumale',
                'date_lieu_nais' => '2000-06-08 à Cotonou',
            ),
            11 => 
            array (
                'id' => 12,
                'matricule' => 'MAT/112E',
                'nom' => 'Sikaou',
                'prenom' => 'Detiou',
                'sex' => 'Masculin',
                'date_naissance' => '2000-02-20',
                'lieu_naissance' => 'Niamey',
                'telephone' => '90399012',
                'compte' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-30 10:09:02',
                'updated_at' => '2023-10-30 10:09:02',
                'deleted_at' => NULL,
                'NomComplet' => 'Sikaou Detiou',
                'date_lieu_nais' => '2000-02-20 à Niamey',
            ),
            12 => 
            array (
                'id' => 13,
                'matricule' => 'MAT/113E',
                'nom' => 'Samiratou',
                'prenom' => 'Gagara',
                'sex' => 'Féminin',
                'date_naissance' => '2000-06-09',
                'lieu_naissance' => 'Niamey',
                'telephone' => '90897867',
                'compte' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-30 10:10:25',
                'updated_at' => '2023-10-30 10:10:25',
                'deleted_at' => NULL,
                'NomComplet' => 'Samiratou Gagara',
                'date_lieu_nais' => '2000-06-09 à Niamey',
            ),
            13 => 
            array (
                'id' => 14,
                'matricule' => 'MAT/114E',
                'nom' => 'Ativon',
                'prenom' => 'K. Justin',
                'sex' => 'Masculin',
                'date_naissance' => '2000-11-11',
                'lieu_naissance' => 'Niamey',
                'telephone' => '99125654',
                'compte' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-30 10:11:48',
                'updated_at' => '2023-10-30 10:11:48',
                'deleted_at' => NULL,
                'NomComplet' => 'Ativon K. Justin',
                'date_lieu_nais' => '2000-11-11 à Niamey',
            ),
            14 => 
            array (
                'id' => 15,
                'matricule' => 'MAT/115E',
                'nom' => 'Capo',
                'prenom' => 'Chi-Chi',
                'sex' => 'Masculin',
                'date_naissance' => '2000-01-04',
                'lieu_naissance' => 'HBD',
                'telephone' => '90201290',
                'compte' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-30 10:13:43',
                'updated_at' => '2023-10-30 10:13:43',
                'deleted_at' => NULL,
                'NomComplet' => 'Capo Chi-Chi',
                'date_lieu_nais' => '2000-01-04 à HBD',
            ),
            15 => 
            array (
                'id' => 16,
                'matricule' => 'MAT/116E',
                'nom' => 'Atamase',
                'prenom' => 'Garba',
                'sex' => 'Masculin',
                'date_naissance' => '2000-05-16',
                'lieu_naissance' => 'Gazawa',
                'telephone' => '90187822',
                'compte' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-30 10:16:15',
                'updated_at' => '2023-10-30 10:16:15',
                'deleted_at' => NULL,
                'NomComplet' => 'Atamase Garba',
                'date_lieu_nais' => '2000-05-16 à Gazawa',
            ),
            16 => 
            array (
                'id' => 17,
                'matricule' => 'MAT/117E',
                'nom' => 'Saidou',
                'prenom' => 'Jariri',
                'sex' => 'Masculin',
                'date_naissance' => '2000-01-31',
                'lieu_naissance' => 'Maradi',
                'telephone' => '90871233',
                'compte' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-30 10:20:17',
                'updated_at' => '2023-10-30 10:20:17',
                'deleted_at' => NULL,
                'NomComplet' => 'Saidou Jariri',
                'date_lieu_nais' => '2000-01-31 à Maradi',
            ),
            17 => 
            array (
                'id' => 18,
                'matricule' => 'MAT/118E',
                'nom' => 'Halidou',
                'prenom' => 'Mahamane',
                'sex' => 'Masculin',
                'date_naissance' => '2000-10-14',
                'lieu_naissance' => 'Dosso',
                'telephone' => '90221923',
                'compte' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-30 10:21:32',
                'updated_at' => '2023-10-30 10:21:32',
                'deleted_at' => NULL,
                'NomComplet' => 'Halidou Mahamane',
                'date_lieu_nais' => '2000-10-14 à Dosso',
            ),
            18 => 
            array (
                'id' => 19,
                'matricule' => 'MAT/119E',
                'nom' => 'Fadi',
                'prenom' => 'Ousman',
                'sex' => 'Féminin',
                'date_naissance' => '2000-07-13',
                'lieu_naissance' => 'Bosso',
                'telephone' => '90881278',
                'compte' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-30 10:23:26',
                'updated_at' => '2023-10-30 10:23:26',
                'deleted_at' => NULL,
                'NomComplet' => 'Fadi Ousman',
                'date_lieu_nais' => '2000-07-13 à Bosso',
            ),
            19 => 
            array (
                'id' => 20,
                'matricule' => 'MAT/120E',
                'nom' => 'Zakaria',
                'prenom' => 'Hamadou',
                'sex' => 'Masculin',
                'date_naissance' => '2000-02-18',
                'lieu_naissance' => 'Niamey',
                'telephone' => '90891211',
                'compte' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-30 10:31:35',
                'updated_at' => '2023-10-30 10:31:35',
                'deleted_at' => NULL,
                'NomComplet' => 'Zakaria Hamadou',
                'date_lieu_nais' => '2000-02-18 à Niamey',
            ),
            20 => 
            array (
                'id' => 21,
                'matricule' => 'MAT/121E',
                'nom' => 'Talatou',
                'prenom' => 'Azumi',
                'sex' => 'Féminin',
                'date_naissance' => '0001-10-20',
                'lieu_naissance' => 'Zinder',
                'telephone' => '90392891',
                'compte' => NULL,
                'etablissement_id' => 1,
                'created_at' => '2023-10-30 10:36:50',
                'updated_at' => '2023-10-30 10:36:50',
                'deleted_at' => NULL,
                'NomComplet' => 'Talatou Azumi',
                'date_lieu_nais' => '0001-10-20 à Zinder',
            ),
        ));
        
        
    }
}