<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class EnseignementAnneesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('enseignement_annees')->delete();
        
        \DB::table('enseignement_annees')->insert(array (
            0 => 
            array (
                'id' => 1,
                'enseignant_id' => 1,
                'niveau_matiere_id' => 1,
                'classe_annee_id' => 1,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:26:06',
                'updated_at' => '2023-10-26 13:26:06',
                'deleted_at' => NULL,
                'code' => 'CI A/Ecriture',
            ),
            1 => 
            array (
                'id' => 2,
                'enseignant_id' => 1,
                'niveau_matiere_id' => 6,
                'classe_annee_id' => 1,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:26:06',
                'updated_at' => '2023-10-26 13:26:06',
                'deleted_at' => NULL,
                'code' => 'CI A/Lecture',
            ),
            2 => 
            array (
                'id' => 3,
                'enseignant_id' => 1,
                'niveau_matiere_id' => 11,
                'classe_annee_id' => 1,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:26:06',
                'updated_at' => '2023-10-26 13:26:06',
                'deleted_at' => NULL,
                'code' => 'CI A/Math',
            ),
            3 => 
            array (
                'id' => 4,
                'enseignant_id' => 1,
                'niveau_matiere_id' => 22,
                'classe_annee_id' => 1,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:26:06',
                'updated_at' => '2023-10-26 13:26:06',
                'deleted_at' => NULL,
                'code' => 'CI A/Dessin',
            ),
            4 => 
            array (
                'id' => 5,
                'enseignant_id' => 1,
                'niveau_matiere_id' => 28,
                'classe_annee_id' => 1,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:26:07',
                'updated_at' => '2023-10-26 13:26:07',
                'deleted_at' => NULL,
                'code' => 'CI A/Moral',
            ),
            5 => 
            array (
                'id' => 6,
                'enseignant_id' => 2,
                'niveau_matiere_id' => 2,
                'classe_annee_id' => 3,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:29:13',
                'updated_at' => '2023-10-26 13:29:13',
                'deleted_at' => NULL,
                'code' => 'CP A/Ecriture',
            ),
            6 => 
            array (
                'id' => 7,
                'enseignant_id' => 2,
                'niveau_matiere_id' => 5,
                'classe_annee_id' => 3,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:29:13',
                'updated_at' => '2023-10-26 13:29:13',
                'deleted_at' => NULL,
                'code' => 'CP A/Lecture',
            ),
            7 => 
            array (
                'id' => 8,
                'enseignant_id' => 2,
                'niveau_matiere_id' => 13,
                'classe_annee_id' => 3,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:29:13',
                'updated_at' => '2023-10-26 13:29:13',
                'deleted_at' => NULL,
                'code' => 'CP A/Math',
            ),
            8 => 
            array (
                'id' => 9,
                'enseignant_id' => 2,
                'niveau_matiere_id' => 21,
                'classe_annee_id' => 3,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:29:13',
                'updated_at' => '2023-10-26 13:29:13',
                'deleted_at' => NULL,
                'code' => 'CP A/Dessin',
            ),
            9 => 
            array (
                'id' => 10,
                'enseignant_id' => 2,
                'niveau_matiere_id' => 27,
                'classe_annee_id' => 3,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:29:13',
                'updated_at' => '2023-10-26 13:29:13',
                'deleted_at' => NULL,
                'code' => 'CP A/Moral',
            ),
            10 => 
            array (
                'id' => 11,
                'enseignant_id' => 3,
                'niveau_matiere_id' => 1,
                'classe_annee_id' => 2,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:32:11',
                'updated_at' => '2023-10-26 13:32:11',
                'deleted_at' => NULL,
                'code' => 'CI B/Ecriture',
            ),
            11 => 
            array (
                'id' => 12,
                'enseignant_id' => 3,
                'niveau_matiere_id' => 6,
                'classe_annee_id' => 2,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:32:11',
                'updated_at' => '2023-10-26 13:32:11',
                'deleted_at' => NULL,
                'code' => 'CI B/Lecture',
            ),
            12 => 
            array (
                'id' => 13,
                'enseignant_id' => 3,
                'niveau_matiere_id' => 11,
                'classe_annee_id' => 2,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:32:11',
                'updated_at' => '2023-10-26 13:32:11',
                'deleted_at' => NULL,
                'code' => 'CI B/Math',
            ),
            13 => 
            array (
                'id' => 14,
                'enseignant_id' => 3,
                'niveau_matiere_id' => 22,
                'classe_annee_id' => 2,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:32:11',
                'updated_at' => '2023-10-26 13:32:11',
                'deleted_at' => NULL,
                'code' => 'CI B/Dessin',
            ),
            14 => 
            array (
                'id' => 15,
                'enseignant_id' => 3,
                'niveau_matiere_id' => 28,
                'classe_annee_id' => 2,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:32:11',
                'updated_at' => '2023-10-26 13:32:11',
                'deleted_at' => NULL,
                'code' => 'CI B/Moral',
            ),
            15 => 
            array (
                'id' => 16,
                'enseignant_id' => 4,
                'niveau_matiere_id' => 2,
                'classe_annee_id' => 4,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:34:03',
                'updated_at' => '2023-10-26 13:34:03',
                'deleted_at' => NULL,
                'code' => 'CP B/Ecriture',
            ),
            16 => 
            array (
                'id' => 17,
                'enseignant_id' => 4,
                'niveau_matiere_id' => 5,
                'classe_annee_id' => 4,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:34:03',
                'updated_at' => '2023-10-26 13:34:03',
                'deleted_at' => NULL,
                'code' => 'CP B/Lecture',
            ),
            17 => 
            array (
                'id' => 18,
                'enseignant_id' => 4,
                'niveau_matiere_id' => 13,
                'classe_annee_id' => 4,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:34:03',
                'updated_at' => '2023-10-26 13:34:03',
                'deleted_at' => NULL,
                'code' => 'CP B/Math',
            ),
            18 => 
            array (
                'id' => 19,
                'enseignant_id' => 4,
                'niveau_matiere_id' => 21,
                'classe_annee_id' => 4,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:34:03',
                'updated_at' => '2023-10-26 13:34:03',
                'deleted_at' => NULL,
                'code' => 'CP B/Dessin',
            ),
            19 => 
            array (
                'id' => 20,
                'enseignant_id' => 4,
                'niveau_matiere_id' => 27,
                'classe_annee_id' => 4,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:34:03',
                'updated_at' => '2023-10-26 13:34:03',
                'deleted_at' => NULL,
                'code' => 'CP B/Moral',
            ),
            20 => 
            array (
                'id' => 21,
                'enseignant_id' => 5,
                'niveau_matiere_id' => 3,
                'classe_annee_id' => 5,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:37:04',
                'updated_at' => '2023-10-26 13:37:04',
                'deleted_at' => NULL,
                'code' => 'CE1/Ecriture',
            ),
            21 => 
            array (
                'id' => 22,
                'enseignant_id' => 5,
                'niveau_matiere_id' => 7,
                'classe_annee_id' => 5,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:37:04',
                'updated_at' => '2023-10-26 13:37:04',
                'deleted_at' => NULL,
                'code' => 'CE1/Lecture',
            ),
            22 => 
            array (
                'id' => 23,
                'enseignant_id' => 5,
                'niveau_matiere_id' => 12,
                'classe_annee_id' => 5,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:37:04',
                'updated_at' => '2023-10-26 13:37:04',
                'deleted_at' => NULL,
                'code' => 'CE1/Math',
            ),
            23 => 
            array (
                'id' => 24,
                'enseignant_id' => 5,
                'niveau_matiere_id' => 20,
                'classe_annee_id' => 5,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:37:04',
                'updated_at' => '2023-10-26 13:37:04',
                'deleted_at' => NULL,
                'code' => 'CE1/Dessin',
            ),
            24 => 
            array (
                'id' => 25,
                'enseignant_id' => 5,
                'niveau_matiere_id' => 26,
                'classe_annee_id' => 5,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:37:04',
                'updated_at' => '2023-10-26 13:37:04',
                'deleted_at' => NULL,
                'code' => 'CE1/Moral',
            ),
            25 => 
            array (
                'id' => 26,
                'enseignant_id' => 6,
                'niveau_matiere_id' => 4,
                'classe_annee_id' => 6,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:40:01',
                'updated_at' => '2023-10-26 13:40:01',
                'deleted_at' => NULL,
                'code' => 'CE2/Ecriture',
            ),
            26 => 
            array (
                'id' => 27,
                'enseignant_id' => 6,
                'niveau_matiere_id' => 8,
                'classe_annee_id' => 6,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:40:01',
                'updated_at' => '2023-10-26 13:40:01',
                'deleted_at' => NULL,
                'code' => 'CE2/Lecture',
            ),
            27 => 
            array (
                'id' => 28,
                'enseignant_id' => 6,
                'niveau_matiere_id' => 14,
                'classe_annee_id' => 6,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:40:01',
                'updated_at' => '2023-10-26 13:40:01',
                'deleted_at' => NULL,
                'code' => 'CE2/Math',
            ),
            28 => 
            array (
                'id' => 29,
                'enseignant_id' => 6,
                'niveau_matiere_id' => 19,
                'classe_annee_id' => 6,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:40:01',
                'updated_at' => '2023-10-26 13:40:01',
                'deleted_at' => NULL,
                'code' => 'CE2/Dessin',
            ),
            29 => 
            array (
                'id' => 30,
                'enseignant_id' => 6,
                'niveau_matiere_id' => 25,
                'classe_annee_id' => 6,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:40:02',
                'updated_at' => '2023-10-26 13:40:02',
                'deleted_at' => NULL,
                'code' => 'CE2/Moral',
            ),
            30 => 
            array (
                'id' => 31,
                'enseignant_id' => 6,
                'niveau_matiere_id' => 31,
                'classe_annee_id' => 6,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:40:02',
                'updated_at' => '2023-10-26 13:40:02',
                'deleted_at' => NULL,
                'code' => 'CE2/ICM',
            ),
            31 => 
            array (
                'id' => 32,
                'enseignant_id' => 6,
                'niveau_matiere_id' => 34,
                'classe_annee_id' => 6,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:40:02',
                'updated_at' => '2023-10-26 13:40:02',
                'deleted_at' => NULL,
                'code' => 'CE2/Etude de texte',
            ),
            32 => 
            array (
                'id' => 33,
                'enseignant_id' => 6,
                'niveau_matiere_id' => 37,
                'classe_annee_id' => 6,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:40:02',
                'updated_at' => '2023-10-26 13:40:02',
                'deleted_at' => NULL,
                'code' => 'CE2/Etude du milieu',
            ),
            33 => 
            array (
                'id' => 34,
                'enseignant_id' => 7,
                'niveau_matiere_id' => 9,
                'classe_annee_id' => 7,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:42:44',
                'updated_at' => '2023-10-26 13:42:44',
                'deleted_at' => NULL,
                'code' => 'CM1/Lecture',
            ),
            34 => 
            array (
                'id' => 35,
                'enseignant_id' => 7,
                'niveau_matiere_id' => 15,
                'classe_annee_id' => 7,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:42:44',
                'updated_at' => '2023-10-26 13:42:44',
                'deleted_at' => NULL,
                'code' => 'CM1/Math',
            ),
            35 => 
            array (
                'id' => 36,
                'enseignant_id' => 7,
                'niveau_matiere_id' => 18,
                'classe_annee_id' => 7,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:42:44',
                'updated_at' => '2023-10-26 13:42:44',
                'deleted_at' => NULL,
                'code' => 'CM1/Dessin',
            ),
            36 => 
            array (
                'id' => 37,
                'enseignant_id' => 7,
                'niveau_matiere_id' => 23,
                'classe_annee_id' => 7,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:42:44',
                'updated_at' => '2023-10-26 13:42:44',
                'deleted_at' => NULL,
                'code' => 'CM1/Moral',
            ),
            37 => 
            array (
                'id' => 38,
                'enseignant_id' => 7,
                'niveau_matiere_id' => 30,
                'classe_annee_id' => 7,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:42:44',
                'updated_at' => '2023-10-26 13:42:44',
                'deleted_at' => NULL,
                'code' => 'CM1/ICM',
            ),
            38 => 
            array (
                'id' => 39,
                'enseignant_id' => 7,
                'niveau_matiere_id' => 33,
                'classe_annee_id' => 7,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:42:44',
                'updated_at' => '2023-10-26 13:42:44',
                'deleted_at' => NULL,
                'code' => 'CM1/Etude de texte',
            ),
            39 => 
            array (
                'id' => 40,
                'enseignant_id' => 7,
                'niveau_matiere_id' => 36,
                'classe_annee_id' => 7,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:42:44',
                'updated_at' => '2023-10-26 13:42:44',
                'deleted_at' => NULL,
                'code' => 'CM1/Etude du milieu',
            ),
            40 => 
            array (
                'id' => 41,
                'enseignant_id' => 8,
                'niveau_matiere_id' => 10,
                'classe_annee_id' => 8,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:45:37',
                'updated_at' => '2023-10-26 13:45:37',
                'deleted_at' => NULL,
                'code' => 'CM2/Lecture',
            ),
            41 => 
            array (
                'id' => 42,
                'enseignant_id' => 8,
                'niveau_matiere_id' => 16,
                'classe_annee_id' => 8,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:45:37',
                'updated_at' => '2023-10-26 13:45:37',
                'deleted_at' => NULL,
                'code' => 'CM2/Math',
            ),
            42 => 
            array (
                'id' => 43,
                'enseignant_id' => 8,
                'niveau_matiere_id' => 17,
                'classe_annee_id' => 8,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:45:37',
                'updated_at' => '2023-10-26 13:45:37',
                'deleted_at' => NULL,
                'code' => 'CM2/Dessin',
            ),
            43 => 
            array (
                'id' => 44,
                'enseignant_id' => 8,
                'niveau_matiere_id' => 24,
                'classe_annee_id' => 8,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:45:37',
                'updated_at' => '2023-10-26 13:45:37',
                'deleted_at' => NULL,
                'code' => 'CM2/Moral',
            ),
            44 => 
            array (
                'id' => 45,
                'enseignant_id' => 8,
                'niveau_matiere_id' => 29,
                'classe_annee_id' => 8,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:45:37',
                'updated_at' => '2023-10-26 13:45:37',
                'deleted_at' => NULL,
                'code' => 'CM2/ICM',
            ),
            45 => 
            array (
                'id' => 46,
                'enseignant_id' => 8,
                'niveau_matiere_id' => 32,
                'classe_annee_id' => 8,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:45:37',
                'updated_at' => '2023-10-26 13:45:37',
                'deleted_at' => NULL,
                'code' => 'CM2/Etude de texte',
            ),
            46 => 
            array (
                'id' => 47,
                'enseignant_id' => 8,
                'niveau_matiere_id' => 35,
                'classe_annee_id' => 8,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:45:37',
                'updated_at' => '2023-10-26 13:45:37',
                'deleted_at' => NULL,
                'code' => 'CM2/Etude du milieu',
            ),
            47 => 
            array (
                'id' => 48,
                'enseignant_id' => 9,
                'niveau_matiere_id' => 38,
                'classe_annee_id' => 1,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:54:33',
                'updated_at' => '2023-10-26 13:54:33',
                'deleted_at' => NULL,
                'code' => 'CI A/Anglais',
            ),
            48 => 
            array (
                'id' => 49,
                'enseignant_id' => 9,
                'niveau_matiere_id' => 38,
                'classe_annee_id' => 2,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:54:33',
                'updated_at' => '2023-10-26 13:54:33',
                'deleted_at' => NULL,
                'code' => 'CI B/Anglais',
            ),
            49 => 
            array (
                'id' => 50,
                'enseignant_id' => 9,
                'niveau_matiere_id' => 39,
                'classe_annee_id' => 3,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:54:33',
                'updated_at' => '2023-10-26 13:54:33',
                'deleted_at' => NULL,
                'code' => 'CP A/Anglais',
            ),
            50 => 
            array (
                'id' => 51,
                'enseignant_id' => 9,
                'niveau_matiere_id' => 39,
                'classe_annee_id' => 4,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:54:33',
                'updated_at' => '2023-10-26 13:54:33',
                'deleted_at' => NULL,
                'code' => 'CP B/Anglais',
            ),
            51 => 
            array (
                'id' => 52,
                'enseignant_id' => 9,
                'niveau_matiere_id' => 40,
                'classe_annee_id' => 5,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:54:33',
                'updated_at' => '2023-10-26 13:54:33',
                'deleted_at' => NULL,
                'code' => 'CE1/Anglais',
            ),
            52 => 
            array (
                'id' => 53,
                'enseignant_id' => 9,
                'niveau_matiere_id' => 41,
                'classe_annee_id' => 6,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:54:33',
                'updated_at' => '2023-10-26 13:54:33',
                'deleted_at' => NULL,
                'code' => 'CE2/Anglais',
            ),
            53 => 
            array (
                'id' => 54,
                'enseignant_id' => 9,
                'niveau_matiere_id' => 42,
                'classe_annee_id' => 7,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:54:33',
                'updated_at' => '2023-10-26 13:54:33',
                'deleted_at' => NULL,
                'code' => 'CM1/Anglais',
            ),
            54 => 
            array (
                'id' => 55,
                'enseignant_id' => 9,
                'niveau_matiere_id' => 43,
                'classe_annee_id' => 8,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:54:33',
                'updated_at' => '2023-10-26 13:54:33',
                'deleted_at' => NULL,
                'code' => 'CM2/Anglais',
            ),
            55 => 
            array (
                'id' => 56,
                'enseignant_id' => 9,
                'niveau_matiere_id' => 38,
                'classe_annee_id' => 9,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:54:33',
                'updated_at' => '2023-10-26 13:54:33',
                'deleted_at' => NULL,
                'code' => 'cv/Anglais',
            ),
            56 => 
            array (
                'id' => 57,
                'enseignant_id' => 10,
                'niveau_matiere_id' => 46,
                'classe_annee_id' => 6,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:56:03',
                'updated_at' => '2023-10-26 13:56:03',
                'deleted_at' => NULL,
                'code' => 'CE2/Informatique',
            ),
            57 => 
            array (
                'id' => 58,
                'enseignant_id' => 10,
                'niveau_matiere_id' => 48,
                'classe_annee_id' => 5,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:56:03',
                'updated_at' => '2023-10-26 13:56:03',
                'deleted_at' => NULL,
                'code' => 'CE1/Informatique',
            ),
            58 => 
            array (
                'id' => 59,
                'enseignant_id' => 10,
                'niveau_matiere_id' => 47,
                'classe_annee_id' => 4,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:56:03',
                'updated_at' => '2023-10-26 13:56:03',
                'deleted_at' => NULL,
                'code' => 'CP B/Informatique',
            ),
            59 => 
            array (
                'id' => 60,
                'enseignant_id' => 10,
                'niveau_matiere_id' => 47,
                'classe_annee_id' => 3,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:56:03',
                'updated_at' => '2023-10-26 13:56:03',
                'deleted_at' => NULL,
                'code' => 'CP A/Informatique',
            ),
            60 => 
            array (
                'id' => 61,
                'enseignant_id' => 10,
                'niveau_matiere_id' => 49,
                'classe_annee_id' => 2,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:56:03',
                'updated_at' => '2023-10-26 13:56:03',
                'deleted_at' => NULL,
                'code' => 'CI B/Informatique',
            ),
            61 => 
            array (
                'id' => 62,
                'enseignant_id' => 10,
                'niveau_matiere_id' => 49,
                'classe_annee_id' => 1,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:56:03',
                'updated_at' => '2023-10-26 13:56:03',
                'deleted_at' => NULL,
                'code' => 'CI A/Informatique',
            ),
            62 => 
            array (
                'id' => 63,
                'enseignant_id' => 10,
                'niveau_matiere_id' => 44,
                'classe_annee_id' => 8,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:56:03',
                'updated_at' => '2023-10-26 13:56:03',
                'deleted_at' => NULL,
                'code' => 'CM2/Informatique',
            ),
            63 => 
            array (
                'id' => 64,
                'enseignant_id' => 10,
                'niveau_matiere_id' => 45,
                'classe_annee_id' => 7,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-26 13:56:03',
                'updated_at' => '2023-10-26 13:56:03',
                'deleted_at' => NULL,
                'code' => 'CM1/Informatique',
            ),
            64 => 
            array (
                'id' => 65,
                'enseignant_id' => 11,
                'niveau_matiere_id' => 91,
                'classe_annee_id' => 11,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:06:50',
                'updated_at' => '2023-10-30 10:06:50',
                'deleted_at' => NULL,
                'code' => '6 eme/Éducation Physique',
            ),
            65 => 
            array (
                'id' => 66,
                'enseignant_id' => 11,
                'niveau_matiere_id' => 90,
                'classe_annee_id' => 12,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:06:50',
                'updated_at' => '2023-10-30 10:06:50',
                'deleted_at' => NULL,
                'code' => '5 eme/Éducation Physique',
            ),
            66 => 
            array (
                'id' => 67,
                'enseignant_id' => 11,
                'niveau_matiere_id' => 89,
                'classe_annee_id' => 13,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:06:50',
                'updated_at' => '2023-10-30 10:06:50',
                'deleted_at' => NULL,
                'code' => '4 eme/Éducation Physique',
            ),
            67 => 
            array (
                'id' => 68,
                'enseignant_id' => 11,
                'niveau_matiere_id' => 88,
                'classe_annee_id' => 14,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:06:50',
                'updated_at' => '2023-10-30 10:06:50',
                'deleted_at' => NULL,
                'code' => '3 eme/Éducation Physique',
            ),
            68 => 
            array (
                'id' => 69,
                'enseignant_id' => 11,
                'niveau_matiere_id' => 87,
                'classe_annee_id' => 15,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:06:50',
                'updated_at' => '2023-10-30 10:06:50',
                'deleted_at' => NULL,
                'code' => 'Seconde A/Éducation Physique',
            ),
            69 => 
            array (
                'id' => 70,
                'enseignant_id' => 11,
                'niveau_matiere_id' => 80,
                'classe_annee_id' => 16,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:06:50',
                'updated_at' => '2023-10-30 10:06:50',
                'deleted_at' => NULL,
                'code' => 'Seconde C/Éducation Physique',
            ),
            70 => 
            array (
                'id' => 71,
                'enseignant_id' => 12,
                'niveau_matiere_id' => 59,
                'classe_annee_id' => 11,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:09:02',
                'updated_at' => '2023-10-30 10:09:02',
                'deleted_at' => NULL,
                'code' => '6 eme/Mathématiques',
            ),
            71 => 
            array (
                'id' => 72,
                'enseignant_id' => 12,
                'niveau_matiere_id' => 60,
                'classe_annee_id' => 12,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:09:02',
                'updated_at' => '2023-10-30 10:09:02',
                'deleted_at' => NULL,
                'code' => '5 eme/Mathématiques',
            ),
            72 => 
            array (
                'id' => 73,
                'enseignant_id' => 12,
                'niveau_matiere_id' => 61,
                'classe_annee_id' => 13,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:09:02',
                'updated_at' => '2023-10-30 10:09:02',
                'deleted_at' => NULL,
                'code' => '4 eme/Mathématiques',
            ),
            73 => 
            array (
                'id' => 74,
                'enseignant_id' => 12,
                'niveau_matiere_id' => 63,
                'classe_annee_id' => 11,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:09:02',
                'updated_at' => '2023-10-30 10:09:02',
                'deleted_at' => NULL,
                'code' => '6 eme/Physique-Chimie',
            ),
            74 => 
            array (
                'id' => 75,
                'enseignant_id' => 13,
                'niveau_matiere_id' => 68,
                'classe_annee_id' => 11,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:10:25',
                'updated_at' => '2023-10-30 10:10:25',
                'deleted_at' => NULL,
                'code' => '6 eme/Économie Familiale',
            ),
            75 => 
            array (
                'id' => 76,
                'enseignant_id' => 13,
                'niveau_matiere_id' => 69,
                'classe_annee_id' => 12,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:10:25',
                'updated_at' => '2023-10-30 10:10:25',
                'deleted_at' => NULL,
                'code' => '5 eme/Économie Familiale',
            ),
            76 => 
            array (
                'id' => 77,
                'enseignant_id' => 13,
                'niveau_matiere_id' => 70,
                'classe_annee_id' => 13,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:10:25',
                'updated_at' => '2023-10-30 10:10:25',
                'deleted_at' => NULL,
                'code' => '4 eme/Économie Familiale',
            ),
            77 => 
            array (
                'id' => 78,
                'enseignant_id' => 13,
                'niveau_matiere_id' => 71,
                'classe_annee_id' => 14,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:10:25',
                'updated_at' => '2023-10-30 10:10:25',
                'deleted_at' => NULL,
                'code' => '3 eme/Économie Familiale',
            ),
            78 => 
            array (
                'id' => 79,
                'enseignant_id' => 13,
                'niveau_matiere_id' => 72,
                'classe_annee_id' => 15,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:10:25',
                'updated_at' => '2023-10-30 10:10:25',
                'deleted_at' => NULL,
                'code' => 'Seconde A/Économie Familiale',
            ),
            79 => 
            array (
                'id' => 80,
                'enseignant_id' => 13,
                'niveau_matiere_id' => 73,
                'classe_annee_id' => 16,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:10:25',
                'updated_at' => '2023-10-30 10:10:25',
                'deleted_at' => NULL,
                'code' => 'Seconde C/Économie Familiale',
            ),
            80 => 
            array (
                'id' => 81,
                'enseignant_id' => 14,
                'niveau_matiere_id' => 64,
                'classe_annee_id' => 11,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:11:48',
                'updated_at' => '2023-10-30 10:11:48',
                'deleted_at' => NULL,
                'code' => '6 eme/S.V.T',
            ),
            81 => 
            array (
                'id' => 82,
                'enseignant_id' => 14,
                'niveau_matiere_id' => 65,
                'classe_annee_id' => 12,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:11:48',
                'updated_at' => '2023-10-30 10:11:48',
                'deleted_at' => NULL,
                'code' => '5 eme/S.V.T',
            ),
            82 => 
            array (
                'id' => 83,
                'enseignant_id' => 14,
                'niveau_matiere_id' => 66,
                'classe_annee_id' => 13,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:11:48',
                'updated_at' => '2023-10-30 10:11:48',
                'deleted_at' => NULL,
                'code' => '4 eme/S.V.T',
            ),
            83 => 
            array (
                'id' => 84,
                'enseignant_id' => 15,
                'niveau_matiere_id' => 62,
                'classe_annee_id' => 14,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:13:43',
                'updated_at' => '2023-10-30 10:13:43',
                'deleted_at' => NULL,
                'code' => '3 eme/Mathématiques',
            ),
            84 => 
            array (
                'id' => 85,
                'enseignant_id' => 15,
                'niveau_matiere_id' => 113,
                'classe_annee_id' => 16,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:13:43',
                'updated_at' => '2023-10-30 10:13:43',
                'deleted_at' => NULL,
                'code' => 'Seconde C/Mathématiques',
            ),
            85 => 
            array (
                'id' => 86,
                'enseignant_id' => 15,
                'niveau_matiere_id' => 112,
                'classe_annee_id' => 16,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:13:43',
                'updated_at' => '2023-10-30 10:13:43',
                'deleted_at' => NULL,
                'code' => 'Seconde C/Physique-Chimie',
            ),
            86 => 
            array (
                'id' => 87,
                'enseignant_id' => 16,
                'niveau_matiere_id' => 106,
                'classe_annee_id' => 12,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:16:15',
                'updated_at' => '2023-10-30 10:16:15',
                'deleted_at' => NULL,
                'code' => '5 eme/Français',
            ),
            87 => 
            array (
                'id' => 88,
                'enseignant_id' => 16,
                'niveau_matiere_id' => 105,
                'classe_annee_id' => 13,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:16:15',
                'updated_at' => '2023-10-30 10:16:15',
                'deleted_at' => NULL,
                'code' => '4 eme/Français',
            ),
            88 => 
            array (
                'id' => 89,
                'enseignant_id' => 16,
                'niveau_matiere_id' => 104,
                'classe_annee_id' => 14,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:16:15',
                'updated_at' => '2023-10-30 10:16:15',
                'deleted_at' => NULL,
                'code' => '3 eme/Français',
            ),
            89 => 
            array (
                'id' => 90,
                'enseignant_id' => 16,
                'niveau_matiere_id' => 57,
                'classe_annee_id' => 11,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:16:15',
                'updated_at' => '2023-10-30 10:16:15',
                'deleted_at' => NULL,
                'code' => '6 eme/Histoire',
            ),
            90 => 
            array (
                'id' => 91,
                'enseignant_id' => 16,
                'niveau_matiere_id' => 58,
                'classe_annee_id' => 11,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:16:15',
                'updated_at' => '2023-10-30 10:16:15',
                'deleted_at' => NULL,
                'code' => '6 eme/Géographie',
            ),
            91 => 
            array (
                'id' => 92,
                'enseignant_id' => 17,
                'niveau_matiere_id' => 107,
                'classe_annee_id' => 12,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:20:17',
                'updated_at' => '2023-10-30 10:20:17',
                'deleted_at' => NULL,
                'code' => '5 eme/Histoire-géographie',
            ),
            92 => 
            array (
                'id' => 93,
                'enseignant_id' => 17,
                'niveau_matiere_id' => 108,
                'classe_annee_id' => 13,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:20:17',
                'updated_at' => '2023-10-30 10:20:17',
                'deleted_at' => NULL,
                'code' => '4 eme/Histoire-géographie',
            ),
            93 => 
            array (
                'id' => 94,
                'enseignant_id' => 17,
                'niveau_matiere_id' => 109,
                'classe_annee_id' => 14,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:20:17',
                'updated_at' => '2023-10-30 10:20:17',
                'deleted_at' => NULL,
                'code' => '3 eme/Histoire-géographie',
            ),
            94 => 
            array (
                'id' => 95,
                'enseignant_id' => 17,
                'niveau_matiere_id' => 110,
                'classe_annee_id' => 16,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:20:17',
                'updated_at' => '2023-10-30 10:20:17',
                'deleted_at' => NULL,
                'code' => 'Seconde C/Histoire-géographie',
            ),
            95 => 
            array (
                'id' => 96,
                'enseignant_id' => 18,
                'niveau_matiere_id' => 67,
                'classe_annee_id' => 14,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:21:32',
                'updated_at' => '2023-10-30 10:21:32',
                'deleted_at' => NULL,
                'code' => '3 eme/S.V.T',
            ),
            96 => 
            array (
                'id' => 97,
                'enseignant_id' => 18,
                'niveau_matiere_id' => 111,
                'classe_annee_id' => 16,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:21:32',
                'updated_at' => '2023-10-30 10:21:32',
                'deleted_at' => NULL,
                'code' => 'Seconde C/S.V.T',
            ),
            97 => 
            array (
                'id' => 98,
                'enseignant_id' => 19,
                'niveau_matiere_id' => 56,
                'classe_annee_id' => 11,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:23:26',
                'updated_at' => '2023-10-30 10:23:26',
                'deleted_at' => NULL,
                'code' => '6 eme/Rédaction',
            ),
            98 => 
            array (
                'id' => 99,
                'enseignant_id' => 19,
                'niveau_matiere_id' => 55,
                'classe_annee_id' => 11,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:23:26',
                'updated_at' => '2023-10-30 10:23:26',
                'deleted_at' => NULL,
                'code' => '6 eme/Dictée question',
            ),
            99 => 
            array (
                'id' => 100,
                'enseignant_id' => 20,
                'niveau_matiere_id' => 114,
                'classe_annee_id' => 16,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:31:35',
                'updated_at' => '2023-10-30 10:31:35',
                'deleted_at' => NULL,
                'code' => 'Seconde C/Français',
            ),
            100 => 
            array (
                'id' => 101,
                'enseignant_id' => 21,
                'niveau_matiere_id' => 50,
                'classe_annee_id' => 11,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:36:50',
                'updated_at' => '2023-10-30 10:36:50',
                'deleted_at' => NULL,
                'code' => '6 eme/Anglais',
            ),
            101 => 
            array (
                'id' => 102,
                'enseignant_id' => 21,
                'niveau_matiere_id' => 51,
                'classe_annee_id' => 12,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:36:50',
                'updated_at' => '2023-10-30 10:36:50',
                'deleted_at' => NULL,
                'code' => '5 eme/Anglais',
            ),
            102 => 
            array (
                'id' => 103,
                'enseignant_id' => 21,
                'niveau_matiere_id' => 52,
                'classe_annee_id' => 13,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:36:50',
                'updated_at' => '2023-10-30 10:36:50',
                'deleted_at' => NULL,
                'code' => '4 eme/Anglais',
            ),
            103 => 
            array (
                'id' => 104,
                'enseignant_id' => 21,
                'niveau_matiere_id' => 53,
                'classe_annee_id' => 14,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:36:50',
                'updated_at' => '2023-10-30 10:36:50',
                'deleted_at' => NULL,
                'code' => '3 eme/Anglais',
            ),
            104 => 
            array (
                'id' => 105,
                'enseignant_id' => 21,
                'niveau_matiere_id' => 54,
                'classe_annee_id' => 16,
                'filiere_niveau_matiere_ue_id' => NULL,
                'created_at' => '2023-10-30 10:36:50',
                'updated_at' => '2023-10-30 10:36:50',
                'deleted_at' => NULL,
                'code' => 'Seconde C/Anglais',
            ),
        ));
        
        
    }
}