<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class EvaluationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('evaluations')->delete();
        
        \DB::table('evaluations')->insert(array (
            0 => 
            array (
                'id' => 1,
                'date' => '2023-11-01',
                'notation' => NULL,
                'pourcentage' => NULL,
                'statut' => 0,
                'session' => 'Prémiere session',
                'periode_id' => 1,
                'type_evaluation_id' => 3,
                'enseignement_annee_id' => 25,
                'created_at' => '2023-11-20 11:36:22',
                'updated_at' => '2023-11-20 11:36:22',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'date' => '2023-11-08',
                'notation' => NULL,
                'pourcentage' => NULL,
                'statut' => 0,
                'session' => 'Prémiere session',
                'periode_id' => 1,
                'type_evaluation_id' => 3,
                'enseignement_annee_id' => 26,
                'created_at' => '2023-11-20 11:37:29',
                'updated_at' => '2023-11-20 11:37:29',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'date' => '2023-10-04',
                'notation' => NULL,
                'pourcentage' => NULL,
                'statut' => 0,
                'session' => 'Prémiere session',
                'periode_id' => 1,
                'type_evaluation_id' => 3,
                'enseignement_annee_id' => 27,
                'created_at' => '2023-11-20 11:38:07',
                'updated_at' => '2023-11-20 11:38:07',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'date' => '2023-11-09',
                'notation' => NULL,
                'pourcentage' => NULL,
                'statut' => 0,
                'session' => 'Prémiere session',
                'periode_id' => 1,
                'type_evaluation_id' => 3,
                'enseignement_annee_id' => 28,
                'created_at' => '2023-11-20 11:38:57',
                'updated_at' => '2023-11-20 11:38:57',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'date' => '2023-11-09',
                'notation' => NULL,
                'pourcentage' => NULL,
                'statut' => 0,
                'session' => 'Prémiere session',
                'periode_id' => 1,
                'type_evaluation_id' => 6,
                'enseignement_annee_id' => 25,
                'created_at' => '2023-11-20 11:39:55',
                'updated_at' => '2023-11-20 11:39:55',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'date' => '2023-11-03',
                'notation' => NULL,
                'pourcentage' => NULL,
                'statut' => 0,
                'session' => 'Prémiere session',
                'periode_id' => 1,
                'type_evaluation_id' => 3,
                'enseignement_annee_id' => 29,
                'created_at' => '2023-11-20 11:40:44',
                'updated_at' => '2023-11-20 11:40:44',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'date' => '2023-11-16',
                'notation' => NULL,
                'pourcentage' => NULL,
                'statut' => 0,
                'session' => 'Prémiere session',
                'periode_id' => 1,
                'type_evaluation_id' => 6,
                'enseignement_annee_id' => 26,
                'created_at' => '2023-11-20 11:41:22',
                'updated_at' => '2023-11-20 11:41:22',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'date' => '2023-11-09',
                'notation' => NULL,
                'pourcentage' => NULL,
                'statut' => 0,
                'session' => 'Prémiere session',
                'periode_id' => 1,
                'type_evaluation_id' => 6,
                'enseignement_annee_id' => 27,
                'created_at' => '2023-11-20 11:43:27',
                'updated_at' => '2023-11-20 11:43:27',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'date' => '2023-11-16',
                'notation' => NULL,
                'pourcentage' => NULL,
                'statut' => 0,
                'session' => 'Prémiere session',
                'periode_id' => 1,
                'type_evaluation_id' => 6,
                'enseignement_annee_id' => 28,
                'created_at' => '2023-11-20 11:44:35',
                'updated_at' => '2023-11-20 11:44:35',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'date' => '2023-11-15',
                'notation' => NULL,
                'pourcentage' => NULL,
                'statut' => 0,
                'session' => 'Prémiere session',
                'periode_id' => 1,
                'type_evaluation_id' => 6,
                'enseignement_annee_id' => 29,
                'created_at' => '2023-11-20 11:45:25',
                'updated_at' => '2023-11-20 11:45:25',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'date' => '2023-11-10',
                'notation' => NULL,
                'pourcentage' => NULL,
                'statut' => 0,
                'session' => 'Prémiere session',
                'periode_id' => 1,
                'type_evaluation_id' => 3,
                'enseignement_annee_id' => 30,
                'created_at' => '2023-11-20 11:46:52',
                'updated_at' => '2023-11-20 11:46:52',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'date' => '2023-11-03',
                'notation' => NULL,
                'pourcentage' => NULL,
                'statut' => 0,
                'session' => 'Prémiere session',
                'periode_id' => 1,
                'type_evaluation_id' => 3,
                'enseignement_annee_id' => 31,
                'created_at' => '2023-11-20 11:47:47',
                'updated_at' => '2023-11-20 11:47:47',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'date' => '2023-11-15',
                'notation' => NULL,
                'pourcentage' => NULL,
                'statut' => 0,
                'session' => 'Prémiere session',
                'periode_id' => 1,
                'type_evaluation_id' => 6,
                'enseignement_annee_id' => 30,
                'created_at' => '2023-11-20 11:48:22',
                'updated_at' => '2023-11-20 11:48:22',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'date' => '2023-11-15',
                'notation' => NULL,
                'pourcentage' => NULL,
                'statut' => 0,
                'session' => 'Prémiere session',
                'periode_id' => 1,
                'type_evaluation_id' => 6,
                'enseignement_annee_id' => 31,
                'created_at' => '2023-11-20 11:48:54',
                'updated_at' => '2023-11-20 11:48:54',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'date' => '2023-10-06',
                'notation' => NULL,
                'pourcentage' => NULL,
                'statut' => 0,
                'session' => 'Prémiere session',
                'periode_id' => 1,
                'type_evaluation_id' => 3,
                'enseignement_annee_id' => 32,
                'created_at' => '2023-11-20 11:50:14',
                'updated_at' => '2023-11-20 11:50:14',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'date' => '2023-10-07',
                'notation' => NULL,
                'pourcentage' => NULL,
                'statut' => 0,
                'session' => 'Prémiere session',
                'periode_id' => 1,
                'type_evaluation_id' => 6,
                'enseignement_annee_id' => 32,
                'created_at' => '2023-11-20 11:51:11',
                'updated_at' => '2023-11-20 11:51:11',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'date' => '2023-09-28',
                'notation' => NULL,
                'pourcentage' => NULL,
                'statut' => 0,
                'session' => 'Prémiere session',
                'periode_id' => 1,
                'type_evaluation_id' => 3,
                'enseignement_annee_id' => 35,
                'created_at' => '2023-11-20 11:52:22',
                'updated_at' => '2023-11-20 11:52:22',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'date' => '2023-10-14',
                'notation' => NULL,
                'pourcentage' => NULL,
                'statut' => 0,
                'session' => 'Prémiere session',
                'periode_id' => 1,
                'type_evaluation_id' => 3,
                'enseignement_annee_id' => 41,
                'created_at' => '2023-11-20 11:52:59',
                'updated_at' => '2023-11-20 11:52:59',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'date' => '2023-11-02',
                'notation' => NULL,
                'pourcentage' => NULL,
                'statut' => 0,
                'session' => 'Prémiere session',
                'periode_id' => 1,
                'type_evaluation_id' => 6,
                'enseignement_annee_id' => 35,
                'created_at' => '2023-11-20 11:53:42',
                'updated_at' => '2023-11-20 11:53:42',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'date' => '2023-11-14',
                'notation' => NULL,
                'pourcentage' => NULL,
                'statut' => 0,
                'session' => 'Prémiere session',
                'periode_id' => 1,
                'type_evaluation_id' => 6,
                'enseignement_annee_id' => 41,
                'created_at' => '2023-11-20 11:54:16',
                'updated_at' => '2023-11-20 11:54:16',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'date' => '2023-11-15',
                'notation' => NULL,
                'pourcentage' => NULL,
                'statut' => 0,
                'session' => 'Prémiere session',
                'periode_id' => 1,
                'type_evaluation_id' => 3,
                'enseignement_annee_id' => 38,
                'created_at' => '2023-11-20 11:56:22',
                'updated_at' => '2023-11-20 11:56:22',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'date' => '2023-11-09',
                'notation' => NULL,
                'pourcentage' => NULL,
                'statut' => 0,
                'session' => 'Prémiere session',
                'periode_id' => 1,
                'type_evaluation_id' => 3,
                'enseignement_annee_id' => 39,
                'created_at' => '2023-11-20 11:57:08',
                'updated_at' => '2023-11-20 11:57:08',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'date' => '2023-11-04',
                'notation' => NULL,
                'pourcentage' => NULL,
                'statut' => 0,
                'session' => 'Prémiere session',
                'periode_id' => 1,
                'type_evaluation_id' => 3,
                'enseignement_annee_id' => 40,
                'created_at' => '2023-11-20 11:57:49',
                'updated_at' => '2023-11-20 11:57:49',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'date' => '2023-11-16',
                'notation' => NULL,
                'pourcentage' => NULL,
                'statut' => 0,
                'session' => 'Prémiere session',
                'periode_id' => 1,
                'type_evaluation_id' => 6,
                'enseignement_annee_id' => 38,
                'created_at' => '2023-11-20 11:58:57',
                'updated_at' => '2023-11-20 11:58:57',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'date' => '2023-11-15',
                'notation' => NULL,
                'pourcentage' => NULL,
                'statut' => 0,
                'session' => 'Prémiere session',
                'periode_id' => 1,
                'type_evaluation_id' => 6,
                'enseignement_annee_id' => 39,
                'created_at' => '2023-11-20 12:01:01',
                'updated_at' => '2023-11-20 12:01:01',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'date' => '2023-11-03',
                'notation' => NULL,
                'pourcentage' => NULL,
                'statut' => 0,
                'session' => 'Prémiere session',
                'periode_id' => 1,
                'type_evaluation_id' => 6,
                'enseignement_annee_id' => 40,
                'created_at' => '2023-11-20 12:02:05',
                'updated_at' => '2023-11-20 12:02:05',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}