<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class FiliereNiveauMatiereUesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('filiere_niveau_matiere_ues')->delete();
        
        \DB::table('filiere_niveau_matiere_ues')->insert(array (
            0 => 
            array (
                'id' => 1,
                'volume_horaire' => '40',
                'coefficient' => '2',
                'cycle_filiere_id' => 1,
                'matiere_id' => 22,
                'niveau_id' => 19,
                'ue_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'volume_horaire' => '40',
                'coefficient' => '2',
                'cycle_filiere_id' => 1,
                'matiere_id' => 23,
                'niveau_id' => 19,
                'ue_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'volume_horaire' => '50',
                'coefficient' => '3',
                'cycle_filiere_id' => 1,
                'matiere_id' => 24,
                'niveau_id' => 19,
                'ue_id' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'volume_horaire' => '50',
                'coefficient' => '5',
                'cycle_filiere_id' => 1,
                'matiere_id' => 25,
                'niveau_id' => 19,
                'ue_id' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'volume_horaire' => '30',
                'coefficient' => '3',
                'cycle_filiere_id' => 1,
                'matiere_id' => 26,
                'niveau_id' => 19,
                'ue_id' => 3,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'volume_horaire' => '40',
                'coefficient' => '4',
                'cycle_filiere_id' => 1,
                'matiere_id' => 27,
                'niveau_id' => 19,
                'ue_id' => 3,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'volume_horaire' => '50',
                'coefficient' => '5',
                'cycle_filiere_id' => 1,
                'matiere_id' => 29,
                'niveau_id' => 19,
                'ue_id' => 3,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'volume_horaire' => '50',
                'coefficient' => '2',
                'cycle_filiere_id' => 7,
                'matiere_id' => 37,
                'niveau_id' => 19,
                'ue_id' => 4,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'volume_horaire' => '25',
                'coefficient' => '1',
                'cycle_filiere_id' => 7,
                'matiere_id' => 38,
                'niveau_id' => 19,
                'ue_id' => 4,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'volume_horaire' => '75',
                'coefficient' => '3',
                'cycle_filiere_id' => 7,
                'matiere_id' => 39,
                'niveau_id' => 19,
                'ue_id' => 5,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'volume_horaire' => '75',
                'coefficient' => '3',
                'cycle_filiere_id' => 7,
                'matiere_id' => 40,
                'niveau_id' => 19,
                'ue_id' => 6,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'volume_horaire' => '100',
                'coefficient' => '4',
                'cycle_filiere_id' => 7,
                'matiere_id' => 41,
                'niveau_id' => 19,
                'ue_id' => 7,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'volume_horaire' => '75',
                'coefficient' => '3',
                'cycle_filiere_id' => 7,
                'matiere_id' => 42,
                'niveau_id' => 19,
                'ue_id' => 8,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'volume_horaire' => '75',
                'coefficient' => '3',
                'cycle_filiere_id' => 7,
                'matiere_id' => 43,
                'niveau_id' => 19,
                'ue_id' => 9,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'volume_horaire' => '50',
                'coefficient' => '2',
                'cycle_filiere_id' => 7,
                'matiere_id' => 44,
                'niveau_id' => 19,
                'ue_id' => 9,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'volume_horaire' => '50',
                'coefficient' => '2',
                'cycle_filiere_id' => 7,
                'matiere_id' => 45,
                'niveau_id' => 19,
                'ue_id' => 10,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'volume_horaire' => '50',
                'coefficient' => '2',
                'cycle_filiere_id' => 7,
                'matiere_id' => 46,
                'niveau_id' => 19,
                'ue_id' => 10,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'volume_horaire' => '50',
                'coefficient' => '2',
                'cycle_filiere_id' => 7,
                'matiere_id' => 47,
                'niveau_id' => 19,
                'ue_id' => 10,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'volume_horaire' => '75',
                'coefficient' => '3',
                'cycle_filiere_id' => 7,
                'matiere_id' => 48,
                'niveau_id' => 19,
                'ue_id' => 11,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'volume_horaire' => '45',
                'coefficient' => '3',
                'cycle_filiere_id' => 7,
                'matiere_id' => 49,
                'niveau_id' => 19,
                'ue_id' => 12,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'volume_horaire' => '45',
                'coefficient' => '3',
                'cycle_filiere_id' => 7,
                'matiere_id' => 50,
                'niveau_id' => 19,
                'ue_id' => 12,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'volume_horaire' => '100',
                'coefficient' => '4',
                'cycle_filiere_id' => 7,
                'matiere_id' => 51,
                'niveau_id' => 19,
                'ue_id' => 13,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'volume_horaire' => '100',
                'coefficient' => '4',
                'cycle_filiere_id' => 7,
                'matiere_id' => 52,
                'niveau_id' => 19,
                'ue_id' => 14,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'volume_horaire' => '100',
                'coefficient' => '4',
                'cycle_filiere_id' => 7,
                'matiere_id' => 53,
                'niveau_id' => 19,
                'ue_id' => 15,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'volume_horaire' => '75',
                'coefficient' => '3',
                'cycle_filiere_id' => 7,
                'matiere_id' => 54,
                'niveau_id' => 19,
                'ue_id' => 16,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'volume_horaire' => '75',
                'coefficient' => '3',
                'cycle_filiere_id' => 7,
                'matiere_id' => 55,
                'niveau_id' => 19,
                'ue_id' => 17,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'volume_horaire' => '75',
                'coefficient' => '3',
                'cycle_filiere_id' => 7,
                'matiere_id' => 56,
                'niveau_id' => 19,
                'ue_id' => 18,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'volume_horaire' => '75',
                'coefficient' => '3',
                'cycle_filiere_id' => 7,
                'matiere_id' => 48,
                'niveau_id' => 19,
                'ue_id' => 19,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'volume_horaire' => '50',
                'coefficient' => '2',
                'cycle_filiere_id' => 7,
                'matiere_id' => 57,
                'niveau_id' => 20,
                'ue_id' => 20,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'volume_horaire' => '50',
                'coefficient' => '2',
                'cycle_filiere_id' => 7,
                'matiere_id' => 58,
                'niveau_id' => 20,
                'ue_id' => 20,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'volume_horaire' => '75',
                'coefficient' => '3',
                'cycle_filiere_id' => 7,
                'matiere_id' => 59,
                'niveau_id' => 20,
                'ue_id' => 21,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'volume_horaire' => '75',
                'coefficient' => '3',
                'cycle_filiere_id' => 7,
                'matiere_id' => 60,
                'niveau_id' => 20,
                'ue_id' => 22,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'volume_horaire' => '75',
                'coefficient' => '3',
                'cycle_filiere_id' => 7,
                'matiere_id' => 61,
                'niveau_id' => 20,
                'ue_id' => 23,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'volume_horaire' => '50',
                'coefficient' => '2',
                'cycle_filiere_id' => 7,
                'matiere_id' => 62,
                'niveau_id' => 20,
                'ue_id' => 24,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'volume_horaire' => '75',
                'coefficient' => '3',
                'cycle_filiere_id' => 7,
                'matiere_id' => 63,
                'niveau_id' => 20,
                'ue_id' => 25,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'volume_horaire' => '75',
                'coefficient' => '3',
                'cycle_filiere_id' => 7,
                'matiere_id' => 64,
                'niveau_id' => 20,
                'ue_id' => 26,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'volume_horaire' => '75',
                'coefficient' => '3',
                'cycle_filiere_id' => 7,
                'matiere_id' => 65,
                'niveau_id' => 20,
                'ue_id' => 27,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'volume_horaire' => '100',
                'coefficient' => '4',
                'cycle_filiere_id' => 7,
                'matiere_id' => 66,
                'niveau_id' => 20,
                'ue_id' => 28,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'volume_horaire' => '50',
                'coefficient' => '2',
                'cycle_filiere_id' => 7,
                'matiere_id' => 48,
                'niveau_id' => 20,
                'ue_id' => 29,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'volume_horaire' => '300',
                'coefficient' => '30',
                'cycle_filiere_id' => 7,
                'matiere_id' => 67,
                'niveau_id' => 20,
                'ue_id' => 30,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}