<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class FraisTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('frais')->delete();
        
        \DB::table('frais')->insert(array (
            0 => 
            array (
                'id' => 1,
                'libelle' => NULL,
                'montant' => 3000.0,
                'etablissement_type_frais_id' => 1,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 11:59:26',
                'updated_at' => '2023-11-13 11:59:26',
            ),
            1 => 
            array (
                'id' => 2,
                'libelle' => NULL,
                'montant' => 3000.0,
                'etablissement_type_frais_id' => 1,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 11:59:26',
                'updated_at' => '2023-11-13 11:59:26',
            ),
            2 => 
            array (
                'id' => 3,
                'libelle' => NULL,
                'montant' => 3000.0,
                'etablissement_type_frais_id' => 1,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 11:59:26',
                'updated_at' => '2023-11-13 11:59:26',
            ),
            3 => 
            array (
                'id' => 4,
                'libelle' => NULL,
                'montant' => 3000.0,
                'etablissement_type_frais_id' => 1,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 4,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 11:59:27',
                'updated_at' => '2023-11-13 11:59:27',
            ),
            4 => 
            array (
                'id' => 5,
                'libelle' => NULL,
                'montant' => 3000.0,
                'etablissement_type_frais_id' => 1,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 6,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 11:59:27',
                'updated_at' => '2023-11-13 11:59:27',
            ),
            5 => 
            array (
                'id' => 6,
                'libelle' => NULL,
                'montant' => 3000.0,
                'etablissement_type_frais_id' => 1,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 5,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 11:59:27',
                'updated_at' => '2023-11-13 11:59:27',
            ),
            6 => 
            array (
                'id' => 7,
                'libelle' => NULL,
                'montant' => 100000.0,
                'etablissement_type_frais_id' => 2,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 11:59:27',
                'updated_at' => '2023-11-13 11:59:27',
            ),
            7 => 
            array (
                'id' => 8,
                'libelle' => NULL,
                'montant' => 100000.0,
                'etablissement_type_frais_id' => 2,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 11:59:27',
                'updated_at' => '2023-11-13 11:59:27',
            ),
            8 => 
            array (
                'id' => 9,
                'libelle' => NULL,
                'montant' => 100000.0,
                'etablissement_type_frais_id' => 2,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 11:59:27',
                'updated_at' => '2023-11-13 11:59:27',
            ),
            9 => 
            array (
                'id' => 10,
                'libelle' => NULL,
                'montant' => 100000.0,
                'etablissement_type_frais_id' => 2,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 4,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 11:59:27',
                'updated_at' => '2023-11-13 11:59:27',
            ),
            10 => 
            array (
                'id' => 11,
                'libelle' => NULL,
                'montant' => 100000.0,
                'etablissement_type_frais_id' => 2,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 6,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 11:59:27',
                'updated_at' => '2023-11-13 11:59:27',
            ),
            11 => 
            array (
                'id' => 12,
                'libelle' => NULL,
                'montant' => 100000.0,
                'etablissement_type_frais_id' => 2,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 5,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 11:59:27',
                'updated_at' => '2023-11-13 11:59:27',
            ),
            12 => 
            array (
                'id' => 13,
                'libelle' => NULL,
                'montant' => 200000.0,
                'etablissement_type_frais_id' => 3,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 7,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 13:05:02',
                'updated_at' => '2023-11-13 13:05:02',
            ),
            13 => 
            array (
                'id' => 14,
                'libelle' => NULL,
                'montant' => 200000.0,
                'etablissement_type_frais_id' => 3,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 8,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 13:05:02',
                'updated_at' => '2023-11-13 13:05:02',
            ),
            14 => 
            array (
                'id' => 15,
                'libelle' => NULL,
                'montant' => 200000.0,
                'etablissement_type_frais_id' => 3,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 9,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 13:05:03',
                'updated_at' => '2023-11-13 13:05:03',
            ),
            15 => 
            array (
                'id' => 16,
                'libelle' => NULL,
                'montant' => 200000.0,
                'etablissement_type_frais_id' => 3,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 10,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 13:05:03',
                'updated_at' => '2023-11-13 13:05:03',
            ),
            16 => 
            array (
                'id' => 17,
                'libelle' => NULL,
                'montant' => 200000.0,
                'etablissement_type_frais_id' => 3,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 11,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 13:05:03',
                'updated_at' => '2023-11-13 13:05:03',
            ),
            17 => 
            array (
                'id' => 18,
                'libelle' => NULL,
                'montant' => 200000.0,
                'etablissement_type_frais_id' => 3,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 12,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 13:05:03',
                'updated_at' => '2023-11-13 13:05:03',
            ),
            18 => 
            array (
                'id' => 19,
                'libelle' => NULL,
                'montant' => 200000.0,
                'etablissement_type_frais_id' => 3,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 13,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 13:05:03',
                'updated_at' => '2023-11-13 13:05:03',
            ),
            19 => 
            array (
                'id' => 20,
                'libelle' => NULL,
                'montant' => 200000.0,
                'etablissement_type_frais_id' => 3,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 15,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 13:05:03',
                'updated_at' => '2023-11-13 13:05:03',
            ),
            20 => 
            array (
                'id' => 21,
                'libelle' => NULL,
                'montant' => 200000.0,
                'etablissement_type_frais_id' => 3,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 14,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 13:05:03',
                'updated_at' => '2023-11-13 13:05:03',
            ),
            21 => 
            array (
                'id' => 22,
                'libelle' => NULL,
                'montant' => 200000.0,
                'etablissement_type_frais_id' => 3,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 13:05:03',
                'updated_at' => '2023-11-13 13:05:03',
            ),
            22 => 
            array (
                'id' => 23,
                'libelle' => NULL,
                'montant' => 200000.0,
                'etablissement_type_frais_id' => 3,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 17,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 13:05:03',
                'updated_at' => '2023-11-13 13:05:03',
            ),
            23 => 
            array (
                'id' => 24,
                'libelle' => NULL,
                'montant' => 200000.0,
                'etablissement_type_frais_id' => 3,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 18,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 13:05:03',
                'updated_at' => '2023-11-13 13:05:03',
            ),
            24 => 
            array (
                'id' => 25,
                'libelle' => NULL,
                'montant' => 5000.0,
                'etablissement_type_frais_id' => 4,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 7,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 13:05:03',
                'updated_at' => '2023-11-13 13:05:03',
            ),
            25 => 
            array (
                'id' => 26,
                'libelle' => NULL,
                'montant' => 5000.0,
                'etablissement_type_frais_id' => 4,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 8,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 13:05:03',
                'updated_at' => '2023-11-13 13:05:03',
            ),
            26 => 
            array (
                'id' => 27,
                'libelle' => NULL,
                'montant' => 5000.0,
                'etablissement_type_frais_id' => 4,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 9,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 13:05:03',
                'updated_at' => '2023-11-13 13:05:03',
            ),
            27 => 
            array (
                'id' => 28,
                'libelle' => NULL,
                'montant' => 5000.0,
                'etablissement_type_frais_id' => 4,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 10,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 13:05:03',
                'updated_at' => '2023-11-13 13:05:03',
            ),
            28 => 
            array (
                'id' => 29,
                'libelle' => NULL,
                'montant' => 5000.0,
                'etablissement_type_frais_id' => 4,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 11,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 13:05:03',
                'updated_at' => '2023-11-13 13:05:03',
            ),
            29 => 
            array (
                'id' => 30,
                'libelle' => NULL,
                'montant' => 5000.0,
                'etablissement_type_frais_id' => 4,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 12,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 13:05:03',
                'updated_at' => '2023-11-13 13:05:03',
            ),
            30 => 
            array (
                'id' => 31,
                'libelle' => NULL,
                'montant' => 5000.0,
                'etablissement_type_frais_id' => 4,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 13,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 13:05:03',
                'updated_at' => '2023-11-13 13:05:03',
            ),
            31 => 
            array (
                'id' => 32,
                'libelle' => NULL,
                'montant' => 5000.0,
                'etablissement_type_frais_id' => 4,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 14,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 13:05:03',
                'updated_at' => '2023-11-13 13:05:03',
            ),
            32 => 
            array (
                'id' => 33,
                'libelle' => NULL,
                'montant' => 5000.0,
                'etablissement_type_frais_id' => 4,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 15,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 13:05:03',
                'updated_at' => '2023-11-13 13:05:03',
            ),
            33 => 
            array (
                'id' => 34,
                'libelle' => NULL,
                'montant' => 5000.0,
                'etablissement_type_frais_id' => 4,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 13:05:03',
                'updated_at' => '2023-11-13 13:05:03',
            ),
            34 => 
            array (
                'id' => 35,
                'libelle' => NULL,
                'montant' => 5000.0,
                'etablissement_type_frais_id' => 4,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 17,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 13:05:03',
                'updated_at' => '2023-11-13 13:05:03',
            ),
            35 => 
            array (
                'id' => 36,
                'libelle' => NULL,
                'montant' => 5000.0,
                'etablissement_type_frais_id' => 4,
                'cycle_filiere_id' => NULL,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 18,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 13:05:03',
                'updated_at' => '2023-11-13 13:05:03',
            ),
            36 => 
            array (
                'id' => 37,
                'libelle' => NULL,
                'montant' => 10000.0,
                'etablissement_type_frais_id' => 5,
                'cycle_filiere_id' => 1,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 19,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 14:50:35',
                'updated_at' => '2023-11-13 14:50:35',
            ),
            37 => 
            array (
                'id' => 38,
                'libelle' => NULL,
                'montant' => 10000.0,
                'etablissement_type_frais_id' => 5,
                'cycle_filiere_id' => 1,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 20,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 14:50:35',
                'updated_at' => '2023-11-13 14:50:35',
            ),
            38 => 
            array (
                'id' => 39,
                'libelle' => NULL,
                'montant' => 10000.0,
                'etablissement_type_frais_id' => 5,
                'cycle_filiere_id' => 1,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 21,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 14:50:35',
                'updated_at' => '2023-11-13 14:50:35',
            ),
            39 => 
            array (
                'id' => 40,
                'libelle' => NULL,
                'montant' => 10000.0,
                'etablissement_type_frais_id' => 5,
                'cycle_filiere_id' => 2,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 19,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 14:50:35',
                'updated_at' => '2023-11-13 14:50:35',
            ),
            40 => 
            array (
                'id' => 41,
                'libelle' => NULL,
                'montant' => 50000.0,
                'etablissement_type_frais_id' => 5,
                'cycle_filiere_id' => 2,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 20,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 14:50:35',
                'updated_at' => '2023-11-13 14:50:35',
            ),
            41 => 
            array (
                'id' => 42,
                'libelle' => NULL,
                'montant' => 650000.0,
                'etablissement_type_frais_id' => 7,
                'cycle_filiere_id' => 1,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 19,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 15:33:46',
                'updated_at' => '2023-11-13 15:33:46',
            ),
            42 => 
            array (
                'id' => 43,
                'libelle' => NULL,
                'montant' => 650000.0,
                'etablissement_type_frais_id' => 7,
                'cycle_filiere_id' => 1,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 20,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 15:33:46',
                'updated_at' => '2023-11-13 15:33:46',
            ),
            43 => 
            array (
                'id' => 44,
                'libelle' => NULL,
                'montant' => 650000.0,
                'etablissement_type_frais_id' => 7,
                'cycle_filiere_id' => 1,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 21,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 15:33:46',
                'updated_at' => '2023-11-13 15:33:46',
            ),
            44 => 
            array (
                'id' => 45,
                'libelle' => NULL,
                'montant' => 650000.0,
                'etablissement_type_frais_id' => 7,
                'cycle_filiere_id' => 2,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 19,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 15:33:46',
                'updated_at' => '2023-11-13 15:33:46',
            ),
            45 => 
            array (
                'id' => 46,
                'libelle' => NULL,
                'montant' => 1200000.0,
                'etablissement_type_frais_id' => 7,
                'cycle_filiere_id' => 2,
                'annee_id' => 2,
                'etablissement_id' => 1,
                'niveau_id' => 20,
                'deleted_at' => NULL,
                'created_at' => '2023-11-13 15:33:46',
                'updated_at' => '2023-11-13 15:33:46',
            ),
        ));
        
        
    }
}