<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class NiveauMatieresTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('niveau_matieres')->delete();
        
        \DB::table('niveau_matieres')->insert(array (
            0 => 
            array (
                'id' => 1,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 3,
                'matiere_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Dictée/CE1',
            ),
            1 => 
            array (
                'id' => 2,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 4,
                'matiere_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Dictée/CE2',
            ),
            2 => 
            array (
                'id' => 3,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 5,
                'matiere_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Dictée/CM1',
            ),
            3 => 
            array (
                'id' => 4,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 6,
                'matiere_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Dictée/CM2',
            ),
            4 => 
            array (
                'id' => 5,
                'volume_horaire' => '20',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 1,
                'matiere_id' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Ecriture/CI',
            ),
            5 => 
            array (
                'id' => 6,
                'volume_horaire' => '20',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 2,
                'matiere_id' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Ecriture/CP',
            ),
            6 => 
            array (
                'id' => 7,
                'volume_horaire' => '20',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 3,
                'matiere_id' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Ecriture/CE1',
            ),
            7 => 
            array (
                'id' => 8,
                'volume_horaire' => '20',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 5,
                'matiere_id' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Ecriture/CM1',
            ),
            8 => 
            array (
                'id' => 9,
                'volume_horaire' => '20',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 4,
                'matiere_id' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Ecriture/CE2',
            ),
            9 => 
            array (
                'id' => 10,
                'volume_horaire' => '20',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 6,
                'matiere_id' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Ecriture/CM2',
            ),
            10 => 
            array (
                'id' => 11,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 3,
                'matiere_id' => 3,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Lecture/CE1',
            ),
            11 => 
            array (
                'id' => 12,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 4,
                'matiere_id' => 3,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Lecture/CE2',
            ),
            12 => 
            array (
                'id' => 13,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 5,
                'matiere_id' => 3,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Lecture/CM1',
            ),
            13 => 
            array (
                'id' => 14,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 6,
                'matiere_id' => 3,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Lecture/CM2',
            ),
            14 => 
            array (
                'id' => 15,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 2,
                'matiere_id' => 3,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Lecture/CP',
            ),
            15 => 
            array (
                'id' => 16,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 1,
                'matiere_id' => 4,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Calcul/CI',
            ),
            16 => 
            array (
                'id' => 17,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 2,
                'matiere_id' => 4,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Calcul/CP',
            ),
            17 => 
            array (
                'id' => 18,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 3,
                'matiere_id' => 4,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Calcul/CE1',
            ),
            18 => 
            array (
                'id' => 19,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 4,
                'matiere_id' => 4,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Calcul/CE2',
            ),
            19 => 
            array (
                'id' => 20,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 6,
                'matiere_id' => 4,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Calcul/CM2',
            ),
            20 => 
            array (
                'id' => 21,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 5,
                'matiere_id' => 4,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Calcul/CM1',
            ),
            21 => 
            array (
                'id' => 22,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 40,
                'niveau_id' => 6,
                'matiere_id' => 5,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Etude de texte/CM2',
            ),
            22 => 
            array (
                'id' => 23,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 40,
                'niveau_id' => 5,
                'matiere_id' => 5,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Etude de texte/CM1',
            ),
            23 => 
            array (
                'id' => 24,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 40,
                'niveau_id' => 3,
                'matiere_id' => 5,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Etude de texte/CE1',
            ),
            24 => 
            array (
                'id' => 25,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 40,
                'niveau_id' => 4,
                'matiere_id' => 5,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Etude de texte/CE2',
            ),
            25 => 
            array (
                'id' => 26,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 30,
                'niveau_id' => 5,
                'matiere_id' => 6,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Etude du milieu/CM1',
            ),
            26 => 
            array (
                'id' => 27,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 30,
                'niveau_id' => 6,
                'matiere_id' => 6,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Etude du milieu/CM2',
            ),
            27 => 
            array (
                'id' => 28,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 30,
                'niveau_id' => 4,
                'matiere_id' => 6,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Etude du milieu/CE2',
            ),
            28 => 
            array (
                'id' => 29,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 30,
                'niveau_id' => 3,
                'matiere_id' => 6,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Etude du milieu/CE1',
            ),
            29 => 
            array (
                'id' => 30,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 2,
                'matiere_id' => 7,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Chant/CP',
            ),
            30 => 
            array (
                'id' => 31,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 3,
                'matiere_id' => 7,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Chant/CE1',
            ),
            31 => 
            array (
                'id' => 32,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 4,
                'matiere_id' => 7,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Chant/CE2',
            ),
            32 => 
            array (
                'id' => 33,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 5,
                'matiere_id' => 7,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Chant/CM1',
            ),
            33 => 
            array (
                'id' => 34,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 6,
                'matiere_id' => 7,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Chant/CM2',
            ),
            34 => 
            array (
                'id' => 35,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 2,
                'matiere_id' => 8,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Récitation/CP',
            ),
            35 => 
            array (
                'id' => 36,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 3,
                'matiere_id' => 8,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Récitation/CE1',
            ),
            36 => 
            array (
                'id' => 37,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 4,
                'matiere_id' => 8,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Récitation/CE2',
            ),
            37 => 
            array (
                'id' => 38,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 5,
                'matiere_id' => 8,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Récitation/CM1',
            ),
            38 => 
            array (
                'id' => 39,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 6,
                'matiere_id' => 8,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Récitation/CM2',
            ),
            39 => 
            array (
                'id' => 40,
                'volume_horaire' => '100',
                'coefficient' => NULL,
                'notation' => 10,
                'niveau_id' => 1,
                'matiere_id' => 7,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Chant/CI',
            ),
            40 => 
            array (
                'id' => 41,
                'volume_horaire' => '100',
                'coefficient' => '3',
                'notation' => NULL,
                'niveau_id' => 7,
                'matiere_id' => 9,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Maths/6e',
            ),
            41 => 
            array (
                'id' => 42,
                'volume_horaire' => '100',
                'coefficient' => '3',
                'notation' => NULL,
                'niveau_id' => 10,
                'matiere_id' => 9,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Maths/3e',
            ),
            42 => 
            array (
                'id' => 43,
                'volume_horaire' => '100',
                'coefficient' => '3',
                'notation' => NULL,
                'niveau_id' => 9,
                'matiere_id' => 9,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Maths/4e',
            ),
            43 => 
            array (
                'id' => 44,
                'volume_horaire' => '100',
                'coefficient' => '3',
                'notation' => NULL,
                'niveau_id' => 8,
                'matiere_id' => 9,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Maths/5e',
            ),
            44 => 
            array (
                'id' => 45,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 7,
                'matiere_id' => 10,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'PC/6e',
            ),
            45 => 
            array (
                'id' => 46,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 8,
                'matiere_id' => 10,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'PC/5e',
            ),
            46 => 
            array (
                'id' => 47,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 9,
                'matiere_id' => 10,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'PC/4e',
            ),
            47 => 
            array (
                'id' => 48,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 10,
                'matiere_id' => 10,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'PC/3e',
            ),
            48 => 
            array (
                'id' => 49,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 11,
                'matiere_id' => 10,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'PC/2nd A',
            ),
            49 => 
            array (
                'id' => 50,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 13,
                'matiere_id' => 10,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'PC/1ere A',
            ),
            50 => 
            array (
                'id' => 51,
                'volume_horaire' => '100',
                'coefficient' => '5',
                'notation' => NULL,
                'niveau_id' => 18,
                'matiere_id' => 9,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Maths/TD',
            ),
            51 => 
            array (
                'id' => 52,
                'volume_horaire' => '100',
                'coefficient' => '5',
                'notation' => NULL,
                'niveau_id' => 17,
                'matiere_id' => 9,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Maths/TC',
            ),
            52 => 
            array (
                'id' => 53,
                'volume_horaire' => '100',
                'coefficient' => '5',
                'notation' => NULL,
                'niveau_id' => 15,
                'matiere_id' => 9,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Maths/1ere D',
            ),
            53 => 
            array (
                'id' => 54,
                'volume_horaire' => '100',
                'coefficient' => '5',
                'notation' => NULL,
                'niveau_id' => 14,
                'matiere_id' => 9,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Maths/1ere C',
            ),
            54 => 
            array (
                'id' => 55,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 7,
                'matiere_id' => 11,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Histoire/Géo/6e',
            ),
            55 => 
            array (
                'id' => 56,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 8,
                'matiere_id' => 11,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Histoire/Géo/5e',
            ),
            56 => 
            array (
                'id' => 57,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 9,
                'matiere_id' => 11,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Histoire/Géo/4e',
            ),
            57 => 
            array (
                'id' => 58,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 10,
                'matiere_id' => 11,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Histoire/Géo/3e',
            ),
            58 => 
            array (
                'id' => 59,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 11,
                'matiere_id' => 11,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Histoire/Géo/2nd A',
            ),
            59 => 
            array (
                'id' => 60,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 12,
                'matiere_id' => 11,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Histoire/Géo/2nd C',
            ),
            60 => 
            array (
                'id' => 61,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 14,
                'matiere_id' => 11,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Histoire/Géo/1ere C',
            ),
            61 => 
            array (
                'id' => 62,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 15,
                'matiere_id' => 11,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Histoire/Géo/1ere D',
            ),
            62 => 
            array (
                'id' => 63,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 17,
                'matiere_id' => 11,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Histoire/Géo/TC',
            ),
            63 => 
            array (
                'id' => 64,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 18,
                'matiere_id' => 11,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Histoire/Géo/TD',
            ),
            64 => 
            array (
                'id' => 65,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 8,
                'matiere_id' => 12,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Anglais/5e',
            ),
            65 => 
            array (
                'id' => 66,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 7,
                'matiere_id' => 12,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Anglais/6e',
            ),
            66 => 
            array (
                'id' => 67,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 9,
                'matiere_id' => 12,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Anglais/4e',
            ),
            67 => 
            array (
                'id' => 68,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 10,
                'matiere_id' => 12,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Anglais/3e',
            ),
            68 => 
            array (
                'id' => 69,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 11,
                'matiere_id' => 12,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Anglais/2nd A',
            ),
            69 => 
            array (
                'id' => 70,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 12,
                'matiere_id' => 12,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Anglais/2nd C',
            ),
            70 => 
            array (
                'id' => 71,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 14,
                'matiere_id' => 12,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Anglais/1ere C',
            ),
            71 => 
            array (
                'id' => 72,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 15,
                'matiere_id' => 12,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Anglais/1ere D',
            ),
            72 => 
            array (
                'id' => 73,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 17,
                'matiere_id' => 12,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Anglais/TC',
            ),
            73 => 
            array (
                'id' => 74,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 18,
                'matiere_id' => 12,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Anglais/TD',
            ),
            74 => 
            array (
                'id' => 75,
                'volume_horaire' => '100',
                'coefficient' => '1',
                'notation' => NULL,
                'niveau_id' => 7,
                'matiere_id' => 13,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'EFS/6e',
            ),
            75 => 
            array (
                'id' => 76,
                'volume_horaire' => '100',
                'coefficient' => '1',
                'notation' => NULL,
                'niveau_id' => 8,
                'matiere_id' => 13,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'EFS/5e',
            ),
            76 => 
            array (
                'id' => 77,
                'volume_horaire' => '100',
                'coefficient' => '1',
                'notation' => NULL,
                'niveau_id' => 9,
                'matiere_id' => 13,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'EFS/4e',
            ),
            77 => 
            array (
                'id' => 78,
                'volume_horaire' => '100',
                'coefficient' => '1',
                'notation' => NULL,
                'niveau_id' => 10,
                'matiere_id' => 13,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'EFS/3e',
            ),
            78 => 
            array (
                'id' => 79,
                'volume_horaire' => '100',
                'coefficient' => '1',
                'notation' => NULL,
                'niveau_id' => 11,
                'matiere_id' => 13,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'EFS/2nd A',
            ),
            79 => 
            array (
                'id' => 80,
                'volume_horaire' => '100',
                'coefficient' => '1',
                'notation' => NULL,
                'niveau_id' => 13,
                'matiere_id' => 13,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'EFS/1ere A',
            ),
            80 => 
            array (
                'id' => 81,
                'volume_horaire' => '100',
                'coefficient' => '1',
                'notation' => NULL,
                'niveau_id' => 12,
                'matiere_id' => 13,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'EFS/2nd C',
            ),
            81 => 
            array (
                'id' => 82,
                'volume_horaire' => '100',
                'coefficient' => '1',
                'notation' => NULL,
                'niveau_id' => 14,
                'matiere_id' => 13,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'EFS/1ere C',
            ),
            82 => 
            array (
                'id' => 83,
                'volume_horaire' => '100',
                'coefficient' => '1',
                'notation' => NULL,
                'niveau_id' => 15,
                'matiere_id' => 13,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'EFS/1ere D',
            ),
            83 => 
            array (
                'id' => 84,
                'volume_horaire' => '100',
                'coefficient' => '1',
                'notation' => NULL,
                'niveau_id' => 16,
                'matiere_id' => 13,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'EFS/TA',
            ),
            84 => 
            array (
                'id' => 85,
                'volume_horaire' => '100',
                'coefficient' => '1',
                'notation' => NULL,
                'niveau_id' => 17,
                'matiere_id' => 13,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'EFS/TC',
            ),
            85 => 
            array (
                'id' => 86,
                'volume_horaire' => '100',
                'coefficient' => '1',
                'notation' => NULL,
                'niveau_id' => 18,
                'matiere_id' => 13,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'EFS/TD',
            ),
            86 => 
            array (
                'id' => 87,
                'volume_horaire' => '100',
                'coefficient' => '1',
                'notation' => NULL,
                'niveau_id' => 12,
                'matiere_id' => 17,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'EPS/2nd C',
            ),
            87 => 
            array (
                'id' => 88,
                'volume_horaire' => '100',
                'coefficient' => '1',
                'notation' => NULL,
                'niveau_id' => 11,
                'matiere_id' => 17,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'EPS/2nd A',
            ),
            88 => 
            array (
                'id' => 89,
                'volume_horaire' => '100',
                'coefficient' => '1',
                'notation' => NULL,
                'niveau_id' => 10,
                'matiere_id' => 17,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'EPS/3e',
            ),
            89 => 
            array (
                'id' => 90,
                'volume_horaire' => '100',
                'coefficient' => '1',
                'notation' => NULL,
                'niveau_id' => 9,
                'matiere_id' => 17,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'EPS/4e',
            ),
            90 => 
            array (
                'id' => 91,
                'volume_horaire' => '100',
                'coefficient' => '1',
                'notation' => NULL,
                'niveau_id' => 8,
                'matiere_id' => 17,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'EPS/5e',
            ),
            91 => 
            array (
                'id' => 92,
                'volume_horaire' => '100',
                'coefficient' => '1',
                'notation' => NULL,
                'niveau_id' => 7,
                'matiere_id' => 17,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'EPS/6e',
            ),
            92 => 
            array (
                'id' => 93,
                'volume_horaire' => '100',
                'coefficient' => '1',
                'notation' => NULL,
                'niveau_id' => 13,
                'matiere_id' => 17,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'EPS/1ere A',
            ),
            93 => 
            array (
                'id' => 94,
                'volume_horaire' => '100',
                'coefficient' => '1',
                'notation' => NULL,
                'niveau_id' => 14,
                'matiere_id' => 17,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'EPS/1ere C',
            ),
            94 => 
            array (
                'id' => 95,
                'volume_horaire' => '100',
                'coefficient' => '1',
                'notation' => NULL,
                'niveau_id' => 15,
                'matiere_id' => 17,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'EPS/1ere D',
            ),
            95 => 
            array (
                'id' => 96,
                'volume_horaire' => '100',
                'coefficient' => '1',
                'notation' => NULL,
                'niveau_id' => 16,
                'matiere_id' => 17,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'EPS/TA',
            ),
            96 => 
            array (
                'id' => 97,
                'volume_horaire' => '100',
                'coefficient' => '1',
                'notation' => NULL,
                'niveau_id' => 17,
                'matiere_id' => 17,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'EPS/TC',
            ),
            97 => 
            array (
                'id' => 98,
                'volume_horaire' => '100',
                'coefficient' => '1',
                'notation' => NULL,
                'niveau_id' => 18,
                'matiere_id' => 17,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'EPS/TD',
            ),
            98 => 
            array (
                'id' => 99,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 13,
                'matiere_id' => 14,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Philo/1ere A',
            ),
            99 => 
            array (
                'id' => 100,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 14,
                'matiere_id' => 14,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Philo/1ere C',
            ),
            100 => 
            array (
                'id' => 101,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 15,
                'matiere_id' => 14,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Philo/1ere D',
            ),
            101 => 
            array (
                'id' => 102,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 16,
                'matiere_id' => 14,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Philo/TA',
            ),
            102 => 
            array (
                'id' => 103,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 17,
                'matiere_id' => 14,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Philo/TC',
            ),
            103 => 
            array (
                'id' => 104,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 18,
                'matiere_id' => 14,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Philo/TD',
            ),
            104 => 
            array (
                'id' => 105,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 11,
                'matiere_id' => 15,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Arabe/2nd A',
            ),
            105 => 
            array (
                'id' => 106,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 16,
                'matiere_id' => 15,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Arabe/TA',
            ),
            106 => 
            array (
                'id' => 107,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 13,
                'matiere_id' => 15,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Arabe/1ere A',
            ),
            107 => 
            array (
                'id' => 108,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 7,
                'matiere_id' => 16,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'SVT/6e',
            ),
            108 => 
            array (
                'id' => 109,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 8,
                'matiere_id' => 16,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'SVT/5e',
            ),
            109 => 
            array (
                'id' => 110,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 9,
                'matiere_id' => 16,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'SVT/4e',
            ),
            110 => 
            array (
                'id' => 111,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 10,
                'matiere_id' => 16,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'SVT/3e',
            ),
            111 => 
            array (
                'id' => 112,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 11,
                'matiere_id' => 16,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'SVT/2nd A',
            ),
            112 => 
            array (
                'id' => 113,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 13,
                'matiere_id' => 16,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'SVT/1ere A',
            ),
            113 => 
            array (
                'id' => 114,
                'volume_horaire' => '100',
                'coefficient' => '2',
                'notation' => NULL,
                'niveau_id' => 14,
                'matiere_id' => 16,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'SVT/1ere C',
            ),
            114 => 
            array (
                'id' => 115,
                'volume_horaire' => '100',
                'coefficient' => '5',
                'notation' => NULL,
                'niveau_id' => 18,
                'matiere_id' => 16,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'SVT/TD',
            ),
        ));
        
        
    }
}