<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class NiveauMatieresTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('niveau_matieres')->delete();
        
        \DB::table('niveau_matieres')->insert(array (
            0 => 
            array (
                'id' => 1,
                'volume_horaire' => '70',
                'notation' => 10,
                'niveau_id' => 1,
                'matiere_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Ecriture/CI',
            ),
            1 => 
            array (
                'id' => 2,
                'volume_horaire' => '70',
                'notation' => 10,
                'niveau_id' => 2,
                'matiere_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Ecriture/CP',
            ),
            2 => 
            array (
                'id' => 3,
                'volume_horaire' => '70',
                'notation' => 10,
                'niveau_id' => 3,
                'matiere_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Ecriture/CE1',
            ),
            3 => 
            array (
                'id' => 4,
                'volume_horaire' => '70',
                'notation' => 5,
                'niveau_id' => 4,
                'matiere_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Ecriture/CE2',
            ),
            4 => 
            array (
                'id' => 5,
                'volume_horaire' => '50',
                'notation' => 10,
                'niveau_id' => 2,
                'matiere_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Lecture/CP',
            ),
            5 => 
            array (
                'id' => 6,
                'volume_horaire' => '50',
                'notation' => 10,
                'niveau_id' => 1,
                'matiere_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Lecture/CI',
            ),
            6 => 
            array (
                'id' => 7,
                'volume_horaire' => '50',
                'notation' => 10,
                'niveau_id' => 3,
                'matiere_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Lecture/CE1',
            ),
            7 => 
            array (
                'id' => 8,
                'volume_horaire' => '50',
                'notation' => 10,
                'niveau_id' => 4,
                'matiere_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Lecture/CE2',
            ),
            8 => 
            array (
                'id' => 9,
                'volume_horaire' => '50',
                'notation' => 10,
                'niveau_id' => 5,
                'matiere_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Lecture/CM1',
            ),
            9 => 
            array (
                'id' => 10,
                'volume_horaire' => '50',
                'notation' => 10,
                'niveau_id' => 6,
                'matiere_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Lecture/CM2',
            ),
            10 => 
            array (
                'id' => 11,
                'volume_horaire' => '60',
                'notation' => 10,
                'niveau_id' => 1,
                'matiere_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Math/CI',
            ),
            11 => 
            array (
                'id' => 12,
                'volume_horaire' => '60',
                'notation' => 40,
                'niveau_id' => 3,
                'matiere_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Math/CE1',
            ),
            12 => 
            array (
                'id' => 13,
                'volume_horaire' => '60',
                'notation' => 10,
                'niveau_id' => 2,
                'matiere_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Math/CP',
            ),
            13 => 
            array (
                'id' => 14,
                'volume_horaire' => '60',
                'notation' => 40,
                'niveau_id' => 4,
                'matiere_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Math/CE2',
            ),
            14 => 
            array (
                'id' => 15,
                'volume_horaire' => '60',
                'notation' => 40,
                'niveau_id' => 5,
                'matiere_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Math/CM1',
            ),
            15 => 
            array (
                'id' => 16,
                'volume_horaire' => '60',
                'notation' => 40,
                'niveau_id' => 6,
                'matiere_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Math/CM2',
            ),
            16 => 
            array (
                'id' => 17,
                'volume_horaire' => '40',
                'notation' => 5,
                'niveau_id' => 6,
                'matiere_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Dessin/CM2',
            ),
            17 => 
            array (
                'id' => 18,
                'volume_horaire' => '40',
                'notation' => 5,
                'niveau_id' => 5,
                'matiere_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Dessin/CM1',
            ),
            18 => 
            array (
                'id' => 19,
                'volume_horaire' => '40',
                'notation' => 5,
                'niveau_id' => 4,
                'matiere_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Dessin/CE2',
            ),
            19 => 
            array (
                'id' => 20,
                'volume_horaire' => '40',
                'notation' => 5,
                'niveau_id' => 3,
                'matiere_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Dessin/CE1',
            ),
            20 => 
            array (
                'id' => 21,
                'volume_horaire' => '40',
                'notation' => 5,
                'niveau_id' => 2,
                'matiere_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Dessin/CP',
            ),
            21 => 
            array (
                'id' => 22,
                'volume_horaire' => '40',
                'notation' => 5,
                'niveau_id' => 1,
                'matiere_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Dessin/CI',
            ),
            22 => 
            array (
                'id' => 23,
                'volume_horaire' => '60',
                'notation' => 10,
                'niveau_id' => 5,
                'matiere_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Moral/CM1',
            ),
            23 => 
            array (
                'id' => 24,
                'volume_horaire' => '60',
                'notation' => 10,
                'niveau_id' => 6,
                'matiere_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Moral/CM2',
            ),
            24 => 
            array (
                'id' => 25,
                'volume_horaire' => '60',
                'notation' => 10,
                'niveau_id' => 4,
                'matiere_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Moral/CE2',
            ),
            25 => 
            array (
                'id' => 26,
                'volume_horaire' => '60',
                'notation' => '1',
                'niveau_id' => 3,
                'matiere_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Moral/CE1',
            ),
            26 => 
            array (
                'id' => 27,
                'volume_horaire' => '60',
                'notation' => 5,
                'niveau_id' => 2,
                'matiere_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Moral/CP',
            ),
            27 => 
            array (
                'id' => 28,
                'volume_horaire' => '60',
                'notation' => 5,
                'niveau_id' => 1,
                'matiere_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Moral/CI',
            ),
            28 => 
            array (
                'id' => 29,
                'volume_horaire' => '50',
                'notation' => 40,
                'niveau_id' => 6,
                'matiere_id' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'ICM/CM2',
            ),
            29 => 
            array (
                'id' => 30,
                'volume_horaire' => '50',
                'notation' => 40,
                'niveau_id' => 5,
                'matiere_id' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'ICM/CM1',
            ),
            30 => 
            array (
                'id' => 31,
                'volume_horaire' => '50',
                'notation' => 40,
                'niveau_id' => 4,
                'matiere_id' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'ICM/CE2',
            ),
            31 => 
            array (
                'id' => 32,
                'volume_horaire' => '60',
                'notation' => 20,
                'niveau_id' => 6,
                'matiere_id' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Etude de texte/CM2',
            ),
            32 => 
            array (
                'id' => 33,
                'volume_horaire' => '60',
                'notation' => 20,
                'niveau_id' => 5,
                'matiere_id' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Etude de texte/CM1',
            ),
            33 => 
            array (
                'id' => 34,
                'volume_horaire' => '60',
                'notation' => 20,
                'niveau_id' => 4,
                'matiere_id' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Etude de texte/CE2',
            ),
            34 => 
            array (
                'id' => 35,
                'volume_horaire' => '70',
                'notation' => 30,
                'niveau_id' => 6,
                'matiere_id' => 9,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Etude du milieu/CM2',
            ),
            35 => 
            array (
                'id' => 36,
                'volume_horaire' => '70',
                'notation' => 30,
                'niveau_id' => 5,
                'matiere_id' => 9,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Etude du milieu/CM1',
            ),
            36 => 
            array (
                'id' => 37,
                'volume_horaire' => '70',
                'notation' => 30,
                'niveau_id' => 4,
                'matiere_id' => 9,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Etude du milieu/CE2',
            ),
            37 => 
            array (
                'id' => 38,
                'volume_horaire' => '30',
                'notation' => 10,
                'niveau_id' => 1,
                'matiere_id' => 30,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Anglais/CI',
            ),
            38 => 
            array (
                'id' => 39,
                'volume_horaire' => '30',
                'notation' => 10,
                'niveau_id' => 2,
                'matiere_id' => 30,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Anglais/CP',
            ),
            39 => 
            array (
                'id' => 40,
                'volume_horaire' => '30',
                'notation' => 10,
                'niveau_id' => 3,
                'matiere_id' => 30,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Anglais/CE1',
            ),
            40 => 
            array (
                'id' => 41,
                'volume_horaire' => '30',
                'notation' => 10,
                'niveau_id' => 4,
                'matiere_id' => 30,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Anglais/CE2',
            ),
            41 => 
            array (
                'id' => 42,
                'volume_horaire' => '30',
                'notation' => 10,
                'niveau_id' => 5,
                'matiere_id' => 30,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Anglais/CM1',
            ),
            42 => 
            array (
                'id' => 43,
                'volume_horaire' => '30',
                'notation' => 10,
                'niveau_id' => 6,
                'matiere_id' => 30,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Anglais/CM2',
            ),
            43 => 
            array (
                'id' => 44,
                'volume_horaire' => '35',
                'notation' => 10,
                'niveau_id' => 6,
                'matiere_id' => 11,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Informatique/CM2',
            ),
            44 => 
            array (
                'id' => 45,
                'volume_horaire' => '35',
                'notation' => 10,
                'niveau_id' => 5,
                'matiere_id' => 11,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Informatique/CM1',
            ),
            45 => 
            array (
                'id' => 46,
                'volume_horaire' => '35',
                'notation' => 10,
                'niveau_id' => 4,
                'matiere_id' => 11,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Informatique/CE2',
            ),
            46 => 
            array (
                'id' => 47,
                'volume_horaire' => '35',
                'notation' => 10,
                'niveau_id' => 2,
                'matiere_id' => 11,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Informatique/CP',
            ),
            47 => 
            array (
                'id' => 48,
                'volume_horaire' => '35',
                'notation' => 10,
                'niveau_id' => 3,
                'matiere_id' => 11,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Informatique/CE1',
            ),
            48 => 
            array (
                'id' => 49,
                'volume_horaire' => '35',
                'notation' => 10,
                'niveau_id' => 1,
                'matiere_id' => 11,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Informatique/CI',
            ),
            49 => 
            array (
                'id' => 50,
                'volume_horaire' => '50',
                'coefficient' => '2',
                'niveau_id' => 7,
                'matiere_id' => 10,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Anglais/6e',
            ),
            50 => 
            array (
                'id' => 51,
                'volume_horaire' => '50',
                'coefficient' => '2',
                'niveau_id' => 8,
                'matiere_id' => 10,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Anglais/5e',
            ),
            51 => 
            array (
                'id' => 52,
                'volume_horaire' => '50',
                'coefficient' => '2',
                'niveau_id' => 9,
                'matiere_id' => 10,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Anglais/4e',
            ),
            52 => 
            array (
                'id' => 53,
                'volume_horaire' => '50',
                'coefficient' => '2',
                'niveau_id' => 10,
                'matiere_id' => 10,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Anglais/3e',
            ),
            53 => 
            array (
                'id' => 54,
                'volume_horaire' => '50',
                'coefficient' => '2',
                'niveau_id' => 12,
                'matiere_id' => 10,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Anglais/2nd C',
            ),
            54 => 
            array (
                'id' => 55,
                'volume_horaire' => '50',
                'coefficient' => '2',
                'niveau_id' => 7,
                'matiere_id' => 17,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Dictée question/6e',
            ),
            55 => 
            array (
                'id' => 56,
                'volume_horaire' => '50',
                'coefficient' => '2',
                'niveau_id' => 7,
                'matiere_id' => 16,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Rédaction/6e',
            ),
            56 => 
            array (
                'id' => 57,
                'volume_horaire' => '30',
                'coefficient' => '1',
                'niveau_id' => 7,
                'matiere_id' => 18,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Histoire/6e',
            ),
            57 => 
            array (
                'id' => 58,
                'volume_horaire' => '30',
                'coefficient' => '1',
                'niveau_id' => 7,
                'matiere_id' => 19,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Géographie/6e',
            ),
            58 => 
            array (
                'id' => 59,
                'volume_horaire' => '70',
                'coefficient' => '3',
                'niveau_id' => 7,
                'matiere_id' => 20,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Mathématiques/6e',
            ),
            59 => 
            array (
                'id' => 60,
                'volume_horaire' => '70',
                'coefficient' => '3',
                'niveau_id' => 8,
                'matiere_id' => 20,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Mathématiques/5e',
            ),
            60 => 
            array (
                'id' => 61,
                'volume_horaire' => '70',
                'coefficient' => '3',
                'niveau_id' => 9,
                'matiere_id' => 20,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Mathématiques/4e',
            ),
            61 => 
            array (
                'id' => 62,
                'volume_horaire' => '70',
                'coefficient' => '3',
                'niveau_id' => 10,
                'matiere_id' => 20,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Mathématiques/3e',
            ),
            62 => 
            array (
                'id' => 63,
                'volume_horaire' => '40',
                'coefficient' => '1',
                'niveau_id' => 7,
                'matiere_id' => 21,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Physique-Chimie/6e',
            ),
            63 => 
            array (
                'id' => 64,
                'volume_horaire' => '60',
                'coefficient' => '2',
                'niveau_id' => 7,
                'matiere_id' => 22,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'S.V.T/6e',
            ),
            64 => 
            array (
                'id' => 65,
                'volume_horaire' => '60',
                'coefficient' => '2',
                'niveau_id' => 8,
                'matiere_id' => 22,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'S.V.T/5e',
            ),
            65 => 
            array (
                'id' => 66,
                'volume_horaire' => '60',
                'coefficient' => '2',
                'niveau_id' => 9,
                'matiere_id' => 22,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'S.V.T/4e',
            ),
            66 => 
            array (
                'id' => 67,
                'volume_horaire' => '60',
                'coefficient' => '2',
                'niveau_id' => 10,
                'matiere_id' => 22,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'S.V.T/3e',
            ),
            67 => 
            array (
                'id' => 68,
                'volume_horaire' => '30',
                'coefficient' => '1',
                'niveau_id' => 7,
                'matiere_id' => 23,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Économie Familiale/6e',
            ),
            68 => 
            array (
                'id' => 69,
                'volume_horaire' => '30',
                'coefficient' => '1',
                'niveau_id' => 8,
                'matiere_id' => 23,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Économie Familiale/5e',
            ),
            69 => 
            array (
                'id' => 70,
                'volume_horaire' => '30',
                'coefficient' => '1',
                'niveau_id' => 9,
                'matiere_id' => 23,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Économie Familiale/4e',
            ),
            70 => 
            array (
                'id' => 71,
                'volume_horaire' => '30',
                'coefficient' => '1',
                'niveau_id' => 10,
                'matiere_id' => 23,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Économie Familiale/3e',
            ),
            71 => 
            array (
                'id' => 72,
                'volume_horaire' => '30',
                'coefficient' => '1',
                'niveau_id' => 11,
                'matiere_id' => 23,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Économie Familiale/2nd A',
            ),
            72 => 
            array (
                'id' => 73,
                'volume_horaire' => '30',
                'coefficient' => '1',
                'niveau_id' => 12,
                'matiere_id' => 23,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Économie Familiale/2nd C',
            ),
            73 => 
            array (
                'id' => 74,
                'volume_horaire' => '30',
                'coefficient' => '1',
                'niveau_id' => 13,
                'matiere_id' => 23,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Économie Familiale/1ere A',
            ),
            74 => 
            array (
                'id' => 75,
                'volume_horaire' => '30',
                'coefficient' => '1',
                'niveau_id' => 14,
                'matiere_id' => 23,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Économie Familiale/1ere C',
            ),
            75 => 
            array (
                'id' => 76,
                'volume_horaire' => '30',
                'coefficient' => '1',
                'niveau_id' => 15,
                'matiere_id' => 23,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Économie Familiale/1ere D',
            ),
            76 => 
            array (
                'id' => 77,
                'volume_horaire' => '30',
                'coefficient' => '1',
                'niveau_id' => 16,
                'matiere_id' => 23,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Économie Familiale/TA',
            ),
            77 => 
            array (
                'id' => 78,
                'volume_horaire' => '30',
                'coefficient' => '1',
                'niveau_id' => 18,
                'matiere_id' => 23,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Économie Familiale/TD',
            ),
            78 => 
            array (
                'id' => 79,
                'volume_horaire' => '30',
                'coefficient' => '1',
                'niveau_id' => 17,
                'matiere_id' => 23,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Économie Familiale/TC',
            ),
            79 => 
            array (
                'id' => 80,
                'volume_horaire' => '30',
                'coefficient' => '1',
                'niveau_id' => 12,
                'matiere_id' => 24,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Éducation Physique/2nd C',
            ),
            80 => 
            array (
                'id' => 81,
                'volume_horaire' => '30',
                'coefficient' => '1',
                'niveau_id' => 17,
                'matiere_id' => 24,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Éducation Physique/TC',
            ),
            81 => 
            array (
                'id' => 82,
                'volume_horaire' => '30',
                'coefficient' => '1',
                'niveau_id' => 18,
                'matiere_id' => 24,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Éducation Physique/TD',
            ),
            82 => 
            array (
                'id' => 83,
                'volume_horaire' => '30',
                'coefficient' => '1',
                'niveau_id' => 16,
                'matiere_id' => 24,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Éducation Physique/TA',
            ),
            83 => 
            array (
                'id' => 84,
                'volume_horaire' => '30',
                'coefficient' => '1',
                'niveau_id' => 15,
                'matiere_id' => 24,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Éducation Physique/1ere D',
            ),
            84 => 
            array (
                'id' => 85,
                'volume_horaire' => '30',
                'coefficient' => '1',
                'niveau_id' => 14,
                'matiere_id' => 24,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Éducation Physique/1ere C',
            ),
            85 => 
            array (
                'id' => 86,
                'volume_horaire' => '30',
                'coefficient' => '1',
                'niveau_id' => 13,
                'matiere_id' => 24,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Éducation Physique/1ere A',
            ),
            86 => 
            array (
                'id' => 87,
                'volume_horaire' => '30',
                'coefficient' => '1',
                'niveau_id' => 11,
                'matiere_id' => 24,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Éducation Physique/2nd A',
            ),
            87 => 
            array (
                'id' => 88,
                'volume_horaire' => '30',
                'coefficient' => '1',
                'niveau_id' => 10,
                'matiere_id' => 24,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Éducation Physique/3e',
            ),
            88 => 
            array (
                'id' => 89,
                'volume_horaire' => '30',
                'coefficient' => '1',
                'niveau_id' => 9,
                'matiere_id' => 24,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Éducation Physique/4e',
            ),
            89 => 
            array (
                'id' => 90,
                'volume_horaire' => '30',
                'coefficient' => '1',
                'niveau_id' => 8,
                'matiere_id' => 24,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Éducation Physique/5e',
            ),
            90 => 
            array (
                'id' => 91,
                'volume_horaire' => '30',
                'coefficient' => '1',
                'niveau_id' => 7,
                'matiere_id' => 24,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Éducation Physique/6e',
            ),
            91 => 
            array (
                'id' => 92,
                'volume_horaire' => '0',
                'coefficient' => '1',
                'niveau_id' => 12,
                'matiere_id' => 25,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Conduite/2nd C',
            ),
            92 => 
            array (
                'id' => 93,
                'volume_horaire' => '0',
                'coefficient' => '1',
                'niveau_id' => 11,
                'matiere_id' => 25,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Conduite/2nd A',
            ),
            93 => 
            array (
                'id' => 94,
                'volume_horaire' => '0',
                'coefficient' => '1',
                'niveau_id' => 10,
                'matiere_id' => 25,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Conduite/3e',
            ),
            94 => 
            array (
                'id' => 95,
                'volume_horaire' => '0',
                'coefficient' => '1',
                'niveau_id' => 9,
                'matiere_id' => 25,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Conduite/4e',
            ),
            95 => 
            array (
                'id' => 96,
                'volume_horaire' => '0',
                'coefficient' => '1',
                'niveau_id' => 8,
                'matiere_id' => 25,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Conduite/5e',
            ),
            96 => 
            array (
                'id' => 97,
                'volume_horaire' => '0',
                'coefficient' => '1',
                'niveau_id' => 7,
                'matiere_id' => 25,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Conduite/6e',
            ),
            97 => 
            array (
                'id' => 98,
                'volume_horaire' => '0',
                'coefficient' => '1',
                'niveau_id' => 13,
                'matiere_id' => 25,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Conduite/1ere A',
            ),
            98 => 
            array (
                'id' => 99,
                'volume_horaire' => '0',
                'coefficient' => '1',
                'niveau_id' => 14,
                'matiere_id' => 25,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Conduite/1ere C',
            ),
            99 => 
            array (
                'id' => 100,
                'volume_horaire' => '0',
                'coefficient' => '1',
                'niveau_id' => 15,
                'matiere_id' => 25,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Conduite/1ere D',
            ),
            100 => 
            array (
                'id' => 101,
                'volume_horaire' => '0',
                'coefficient' => '1',
                'niveau_id' => 16,
                'matiere_id' => 25,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Conduite/TA',
            ),
            101 => 
            array (
                'id' => 102,
                'volume_horaire' => '0',
                'coefficient' => '1',
                'niveau_id' => 17,
                'matiere_id' => 25,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Conduite/TC',
            ),
            102 => 
            array (
                'id' => 103,
                'volume_horaire' => '0',
                'coefficient' => '1',
                'niveau_id' => 18,
                'matiere_id' => 25,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Conduite/TD',
            ),
            103 => 
            array (
                'id' => 104,
                'volume_horaire' => '80',
                'coefficient' => '4',
                'niveau_id' => 10,
                'matiere_id' => 26,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Français/3e',
            ),
            104 => 
            array (
                'id' => 105,
                'volume_horaire' => '80',
                'coefficient' => '4',
                'niveau_id' => 9,
                'matiere_id' => 26,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Français/4e',
            ),
            105 => 
            array (
                'id' => 106,
                'volume_horaire' => '80',
                'coefficient' => '4',
                'niveau_id' => 8,
                'matiere_id' => 26,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Français/5e',
            ),
            106 => 
            array (
                'id' => 107,
                'volume_horaire' => '60',
                'coefficient' => '2',
                'niveau_id' => 8,
                'matiere_id' => 27,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Histoire-géographie/5e',
            ),
            107 => 
            array (
                'id' => 108,
                'volume_horaire' => '60',
                'coefficient' => '2',
                'niveau_id' => 9,
                'matiere_id' => 27,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Histoire-géographie/4e',
            ),
            108 => 
            array (
                'id' => 109,
                'volume_horaire' => '60',
                'coefficient' => '2',
                'niveau_id' => 10,
                'matiere_id' => 27,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Histoire-géographie/3e',
            ),
            109 => 
            array (
                'id' => 110,
                'volume_horaire' => '60',
                'coefficient' => '2',
                'niveau_id' => 12,
                'matiere_id' => 27,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Histoire-géographie/2nd C',
            ),
            110 => 
            array (
                'id' => 111,
                'volume_horaire' => '80',
                'coefficient' => '3',
                'niveau_id' => 12,
                'matiere_id' => 22,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'S.V.T/2nd C',
            ),
            111 => 
            array (
                'id' => 112,
                'volume_horaire' => '80',
                'coefficient' => '4',
                'niveau_id' => 12,
                'matiere_id' => 21,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Physique-Chimie/2nd C',
            ),
            112 => 
            array (
                'id' => 113,
                'volume_horaire' => '100',
                'coefficient' => '4',
                'niveau_id' => 12,
                'matiere_id' => 20,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Mathématiques/2nd C',
            ),
            113 => 
            array (
                'id' => 114,
                'volume_horaire' => '100',
                'coefficient' => '4',
                'niveau_id' => 12,
                'matiere_id' => 26,
                'created_at' => NULL,
                'updated_at' => NULL,
                'code' => 'Français/2nd C',
            ),
        ));
        
        
    }
}