/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VDataTable: typeof import('vuetify/labs/VDataTable')['VDataTable']
    VStepper: typeof import('vuetify/labs/VStepper')['VStepper']
    VStepperHeader: typeof import('vuetify/lib')['VStepperHeader']
    VStepperItem: typeof import('vuetify/lib')['VStepperItem']
  }
}
